# SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
#
# SPDX-License-Identifier: MIT

misconfigurations:
  - id: AVD-DS-0002
    paths:
      - "Containerfile.dsh"
      - "Containerfile.gateway"
      - "Containerfile.guestagent"
      - "Containerfile.orchestrator"
    statement: "The orchestrator, guest-agent and gateway containers run as root intentionally"
