# SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
#
# SPDX-License-Identifier: MIT

FROM scratch
ENV PATH=/bin
ARG TARGETOS
ARG TARGETARCH
COPY bin/${TARGETOS}-${TARGETARCH}/dsh-podman-orchestrator /bin/dsh-podman-orchestrator
COPY LICENSE.pkg /usr/share/licenses/dsh-podman/LICENSE.pkg
ENTRYPOINT ["/bin/dsh-podman-orchestrator"]
