# SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
#
# SPDX-License-Identifier: MIT

*
!bin/
!bin/linux-amd64/
!bin/linux-arm64/
!bin/linux-amd64/dsh-podman-orchestrator
!bin/linux-arm64/dsh-podman-orchestrator
!LICENSE.pkg