# SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
#
# SPDX-License-Identifier: MIT

FROM scratch
ENV PATH=/bin
ARG TARGETOS
ARG TARGETARCH
COPY bin/${TARGETOS}-${TARGETARCH}/dsh-podman-guest-agent /bin/dsh-podman-guest-agent
ENTRYPOINT ["/bin/dsh-podman-guest-agent"]
