// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dshgateway/v1/gateway.proto

package dshgatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol is the transport a published port speaks. Only TCP is implemented;
// the others are reserved so the wire format does not have to change.
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
	Protocol_PROTOCOL_HTTP        Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
		3: "PROTOCOL_HTTP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
		"PROTOCOL_HTTP":        3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_dshgateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_dshgateway_v1_gateway_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type GetVersionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit  string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// A random id generated once per gateway process, so a caller can tell a
	// live gateway from a restarted one and re-establish its bindings.
	Instance      string `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type BindRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The guest container's podman name, which locates its socket directory
	// under the socket root. Internal to the deployment; never returned.
	PodmanName string `protobuf:"bytes,1,opt,name=podman_name,json=podmanName,proto3" json:"podman_name,omitempty"`
	// The socket file name inside that directory, e.g. "t8080".
	SocketName string   `protobuf:"bytes,2,opt,name=socket_name,json=socketName,proto3" json:"socket_name,omitempty"`
	Protocol   Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=dshgateway.v1.Protocol" json:"protocol,omitempty"`
	// The host port to prefer. 0 asks the gateway to choose a free one.
	SuggestedHostPort uint32 `protobuf:"varint,4,opt,name=suggested_host_port,json=suggestedHostPort,proto3" json:"suggested_host_port,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BindRequest) GetPodmanName() string {
	if x != nil {
		return x.PodmanName
	}
	return ""
}

func (x *BindRequest) GetSocketName() string {
	if x != nil {
		return x.SocketName
	}
	return ""
}

func (x *BindRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *BindRequest) GetSuggestedHostPort() uint32 {
	if x != nil {
		return x.SuggestedHostPort
	}
	return 0
}

// The address is returned alongside the port because the gateway owns the
// address: loopback today, a hostname once HTTP publishing lands.
type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *BindResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BindResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type UnbindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodmanName    string                 `protobuf:"bytes,1,opt,name=podman_name,json=podmanName,proto3" json:"podman_name,omitempty"`
	SocketName    string                 `protobuf:"bytes,2,opt,name=socket_name,json=socketName,proto3" json:"socket_name,omitempty"`
	Protocol      Protocol               `protobuf:"varint,3,opt,name=protocol,proto3,enum=dshgateway.v1.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRequest) Reset() {
	*x = UnbindRequest{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRequest) ProtoMessage() {}

func (x *UnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRequest.ProtoReflect.Descriptor instead.
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *UnbindRequest) GetPodmanName() string {
	if x != nil {
		return x.PodmanName
	}
	return ""
}

func (x *UnbindRequest) GetSocketName() string {
	if x != nil {
		return x.SocketName
	}
	return ""
}

func (x *UnbindRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

type UnbindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindResponse) Reset() {
	*x = UnbindResponse{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResponse) ProtoMessage() {}

func (x *UnbindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResponse.ProtoReflect.Descriptor instead.
func (*UnbindResponse) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*Binding             `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type Binding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodmanName    string                 `protobuf:"bytes,1,opt,name=podman_name,json=podmanName,proto3" json:"podman_name,omitempty"`
	SocketName    string                 `protobuf:"bytes,2,opt,name=socket_name,json=socketName,proto3" json:"socket_name,omitempty"`
	Protocol      Protocol               `protobuf:"varint,3,opt,name=protocol,proto3,enum=dshgateway.v1.Protocol" json:"protocol,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *Binding) GetPodmanName() string {
	if x != nil {
		return x.PodmanName
	}
	return ""
}

func (x *Binding) GetSocketName() string {
	if x != nil {
		return x.SocketName
	}
	return ""
}

func (x *Binding) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Binding) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Binding) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// LeaseRequest is a liveness ping; LeaseResponse acknowledges one. An empty
// request is a valid ping and an empty response a valid acknowledgement.
type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

type LeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshgateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_dshgateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

var File_dshgateway_v1_gateway_proto protoreflect.FileDescriptor

const file_dshgateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bdshgateway/v1/gateway.proto\x12\rdshgateway.v1\"\x13\n" +
	"\x11GetVersionRequest\"b\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1a\n" +
	"\binstance\x18\x03 \x01(\tR\binstance\"\xb4\x01\n" +
	"\vBindRequest\x12\x1f\n" +
	"\vpodman_name\x18\x01 \x01(\tR\n" +
	"podmanName\x12\x1f\n" +
	"\vsocket_name\x18\x02 \x01(\tR\n" +
	"socketName\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.dshgateway.v1.ProtocolR\bprotocol\x12.\n" +
	"\x13suggested_host_port\x18\x04 \x01(\rR\x11suggestedHostPort\"<\n" +
	"\fBindResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x86\x01\n" +
	"\rUnbindRequest\x12\x1f\n" +
	"\vpodman_name\x18\x01 \x01(\tR\n" +
	"podmanName\x12\x1f\n" +
	"\vsocket_name\x18\x02 \x01(\tR\n" +
	"socketName\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.dshgateway.v1.ProtocolR\bprotocol\"\x10\n" +
	"\x0eUnbindResponse\"\r\n" +
	"\vListRequest\"B\n" +
	"\fListResponse\x122\n" +
	"\bbindings\x18\x01 \x03(\v2\x16.dshgateway.v1.BindingR\bbindings\"\xae\x01\n" +
	"\aBinding\x12\x1f\n" +
	"\vpodman_name\x18\x01 \x01(\tR\n" +
	"podmanName\x12\x1f\n" +
	"\vsocket_name\x18\x02 \x01(\tR\n" +
	"socketName\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.dshgateway.v1.ProtocolR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\"\x0e\n" +
	"\fLeaseRequest\"\x0f\n" +
	"\rLeaseResponse*[\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02\x12\x11\n" +
	"\rPROTOCOL_HTTP\x10\x032\xed\x02\n" +
	"\aGateway\x12Q\n" +
	"\n" +
	"GetVersion\x12 .dshgateway.v1.GetVersionRequest\x1a!.dshgateway.v1.GetVersionResponse\x12?\n" +
	"\x04Bind\x12\x1a.dshgateway.v1.BindRequest\x1a\x1b.dshgateway.v1.BindResponse\x12E\n" +
	"\x06Unbind\x12\x1c.dshgateway.v1.UnbindRequest\x1a\x1d.dshgateway.v1.UnbindResponse\x12?\n" +
	"\x04List\x12\x1a.dshgateway.v1.ListRequest\x1a\x1b.dshgateway.v1.ListResponse\x12F\n" +
	"\x05Lease\x12\x1b.dshgateway.v1.LeaseRequest\x1a\x1c.dshgateway.v1.LeaseResponse(\x010\x01BOZMgithub.com/Exagone313/dsh-podman/internal/genproto/dshgateway/v1;dshgatewayv1b\x06proto3"

var (
	file_dshgateway_v1_gateway_proto_rawDescOnce sync.Once
	file_dshgateway_v1_gateway_proto_rawDescData []byte
)

func file_dshgateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_dshgateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_dshgateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dshgateway_v1_gateway_proto_rawDesc), len(file_dshgateway_v1_gateway_proto_rawDesc)))
	})
	return file_dshgateway_v1_gateway_proto_rawDescData
}

var file_dshgateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dshgateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dshgateway_v1_gateway_proto_goTypes = []any{
	(Protocol)(0),              // 0: dshgateway.v1.Protocol
	(*GetVersionRequest)(nil),  // 1: dshgateway.v1.GetVersionRequest
	(*GetVersionResponse)(nil), // 2: dshgateway.v1.GetVersionResponse
	(*BindRequest)(nil),        // 3: dshgateway.v1.BindRequest
	(*BindResponse)(nil),       // 4: dshgateway.v1.BindResponse
	(*UnbindRequest)(nil),      // 5: dshgateway.v1.UnbindRequest
	(*UnbindResponse)(nil),     // 6: dshgateway.v1.UnbindResponse
	(*ListRequest)(nil),        // 7: dshgateway.v1.ListRequest
	(*ListResponse)(nil),       // 8: dshgateway.v1.ListResponse
	(*Binding)(nil),            // 9: dshgateway.v1.Binding
	(*LeaseRequest)(nil),       // 10: dshgateway.v1.LeaseRequest
	(*LeaseResponse)(nil),      // 11: dshgateway.v1.LeaseResponse
}
var file_dshgateway_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: dshgateway.v1.BindRequest.protocol:type_name -> dshgateway.v1.Protocol
	0,  // 1: dshgateway.v1.UnbindRequest.protocol:type_name -> dshgateway.v1.Protocol
	9,  // 2: dshgateway.v1.ListResponse.bindings:type_name -> dshgateway.v1.Binding
	0,  // 3: dshgateway.v1.Binding.protocol:type_name -> dshgateway.v1.Protocol
	1,  // 4: dshgateway.v1.Gateway.GetVersion:input_type -> dshgateway.v1.GetVersionRequest
	3,  // 5: dshgateway.v1.Gateway.Bind:input_type -> dshgateway.v1.BindRequest
	5,  // 6: dshgateway.v1.Gateway.Unbind:input_type -> dshgateway.v1.UnbindRequest
	7,  // 7: dshgateway.v1.Gateway.List:input_type -> dshgateway.v1.ListRequest
	10, // 8: dshgateway.v1.Gateway.Lease:input_type -> dshgateway.v1.LeaseRequest
	2,  // 9: dshgateway.v1.Gateway.GetVersion:output_type -> dshgateway.v1.GetVersionResponse
	4,  // 10: dshgateway.v1.Gateway.Bind:output_type -> dshgateway.v1.BindResponse
	6,  // 11: dshgateway.v1.Gateway.Unbind:output_type -> dshgateway.v1.UnbindResponse
	8,  // 12: dshgateway.v1.Gateway.List:output_type -> dshgateway.v1.ListResponse
	11, // 13: dshgateway.v1.Gateway.Lease:output_type -> dshgateway.v1.LeaseResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dshgateway_v1_gateway_proto_init() }
func file_dshgateway_v1_gateway_proto_init() {
	if File_dshgateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dshgateway_v1_gateway_proto_rawDesc), len(file_dshgateway_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dshgateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_dshgateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_dshgateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_dshgateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_dshgateway_v1_gateway_proto = out.File
	file_dshgateway_v1_gateway_proto_goTypes = nil
	file_dshgateway_v1_gateway_proto_depIdxs = nil
}
