// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dshctl/v1/control.proto

package dshctlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorControl_ListProjects_FullMethodName          = "/dshctl.v1.OrchestratorControl/ListProjects"
	OrchestratorControl_CreateWorkspace_FullMethodName       = "/dshctl.v1.OrchestratorControl/CreateWorkspace"
	OrchestratorControl_DescribeWorkspace_FullMethodName     = "/dshctl.v1.OrchestratorControl/DescribeWorkspace"
	OrchestratorControl_ListWorkspaces_FullMethodName        = "/dshctl.v1.OrchestratorControl/ListWorkspaces"
	OrchestratorControl_ListImages_FullMethodName            = "/dshctl.v1.OrchestratorControl/ListImages"
	OrchestratorControl_GetImage_FullMethodName              = "/dshctl.v1.OrchestratorControl/GetImage"
	OrchestratorControl_BuildImage_FullMethodName            = "/dshctl.v1.OrchestratorControl/BuildImage"
	OrchestratorControl_RebuildImage_FullMethodName          = "/dshctl.v1.OrchestratorControl/RebuildImage"
	OrchestratorControl_RebuildAllImages_FullMethodName      = "/dshctl.v1.OrchestratorControl/RebuildAllImages"
	OrchestratorControl_RemoveImage_FullMethodName           = "/dshctl.v1.OrchestratorControl/RemoveImage"
	OrchestratorControl_RebuildBaseImage_FullMethodName      = "/dshctl.v1.OrchestratorControl/RebuildBaseImage"
	OrchestratorControl_PullBaseImage_FullMethodName         = "/dshctl.v1.OrchestratorControl/PullBaseImage"
	OrchestratorControl_ListContainers_FullMethodName        = "/dshctl.v1.OrchestratorControl/ListContainers"
	OrchestratorControl_StartContainer_FullMethodName        = "/dshctl.v1.OrchestratorControl/StartContainer"
	OrchestratorControl_RecreateContainer_FullMethodName     = "/dshctl.v1.OrchestratorControl/RecreateContainer"
	OrchestratorControl_RemoveContainer_FullMethodName       = "/dshctl.v1.OrchestratorControl/RemoveContainer"
	OrchestratorControl_AddContainerMount_FullMethodName     = "/dshctl.v1.OrchestratorControl/AddContainerMount"
	OrchestratorControl_RemoveContainerMount_FullMethodName  = "/dshctl.v1.OrchestratorControl/RemoveContainerMount"
	OrchestratorControl_ListVolumes_FullMethodName           = "/dshctl.v1.OrchestratorControl/ListVolumes"
	OrchestratorControl_CreateVolume_FullMethodName          = "/dshctl.v1.OrchestratorControl/CreateVolume"
	OrchestratorControl_RemoveVolume_FullMethodName          = "/dshctl.v1.OrchestratorControl/RemoveVolume"
	OrchestratorControl_ListSecrets_FullMethodName           = "/dshctl.v1.OrchestratorControl/ListSecrets"
	OrchestratorControl_CreateSecret_FullMethodName          = "/dshctl.v1.OrchestratorControl/CreateSecret"
	OrchestratorControl_WriteSecretValue_FullMethodName      = "/dshctl.v1.OrchestratorControl/WriteSecretValue"
	OrchestratorControl_RemoveSecret_FullMethodName          = "/dshctl.v1.OrchestratorControl/RemoveSecret"
	OrchestratorControl_AddContainerSecret_FullMethodName    = "/dshctl.v1.OrchestratorControl/AddContainerSecret"
	OrchestratorControl_RemoveContainerSecret_FullMethodName = "/dshctl.v1.OrchestratorControl/RemoveContainerSecret"
)

// OrchestratorControlClient is the client API for OrchestratorControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorControlClient interface {
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	DescribeWorkspace(ctx context.Context, in *DescribeWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error)
	BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*Image, error)
	RebuildImage(ctx context.Context, in *RebuildImageRequest, opts ...grpc.CallOption) (*Image, error)
	RebuildAllImages(ctx context.Context, in *RebuildAllImagesRequest, opts ...grpc.CallOption) (*RebuildAllImagesResponse, error)
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	RebuildBaseImage(ctx context.Context, in *RebuildBaseImageRequest, opts ...grpc.CallOption) (*Image, error)
	PullBaseImage(ctx context.Context, in *PullBaseImageRequest, opts ...grpc.CallOption) (*Image, error)
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*Container, error)
	RecreateContainer(ctx context.Context, in *RecreateContainerRequest, opts ...grpc.CallOption) (*Workspace, error)
	RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error)
	AddContainerMount(ctx context.Context, in *AddContainerMountRequest, opts ...grpc.CallOption) (*Container, error)
	RemoveContainerMount(ctx context.Context, in *RemoveContainerMountRequest, opts ...grpc.CallOption) (*Container, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	WriteSecretValue(ctx context.Context, in *WriteSecretValueRequest, opts ...grpc.CallOption) (*Secret, error)
	RemoveSecret(ctx context.Context, in *RemoveSecretRequest, opts ...grpc.CallOption) (*RemoveSecretResponse, error)
	AddContainerSecret(ctx context.Context, in *AddContainerSecretRequest, opts ...grpc.CallOption) (*Container, error)
	RemoveContainerSecret(ctx context.Context, in *RemoveContainerSecretRequest, opts ...grpc.CallOption) (*Container, error)
}

type orchestratorControlClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorControlClient(cc grpc.ClientConnInterface) OrchestratorControlClient {
	return &orchestratorControlClient{cc}
}

func (c *orchestratorControlClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, OrchestratorControl_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) DescribeWorkspace(ctx context.Context, in *DescribeWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, OrchestratorControl_DescribeWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, OrchestratorControl_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, OrchestratorControl_BuildImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RebuildImage(ctx context.Context, in *RebuildImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, OrchestratorControl_RebuildImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RebuildAllImages(ctx context.Context, in *RebuildAllImagesRequest, opts ...grpc.CallOption) (*RebuildAllImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildAllImagesResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_RebuildAllImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RebuildBaseImage(ctx context.Context, in *RebuildBaseImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, OrchestratorControl_RebuildBaseImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) PullBaseImage(ctx context.Context, in *PullBaseImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, OrchestratorControl_PullBaseImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*Container, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Container)
	err := c.cc.Invoke(ctx, OrchestratorControl_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RecreateContainer(ctx context.Context, in *RecreateContainerRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, OrchestratorControl_RecreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveContainerResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) AddContainerMount(ctx context.Context, in *AddContainerMountRequest, opts ...grpc.CallOption) (*Container, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Container)
	err := c.cc.Invoke(ctx, OrchestratorControl_AddContainerMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveContainerMount(ctx context.Context, in *RemoveContainerMountRequest, opts ...grpc.CallOption) (*Container, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Container)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveContainerMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, OrchestratorControl_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVolumeResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, OrchestratorControl_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) WriteSecretValue(ctx context.Context, in *WriteSecretValueRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, OrchestratorControl_WriteSecretValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveSecret(ctx context.Context, in *RemoveSecretRequest, opts ...grpc.CallOption) (*RemoveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSecretResponse)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) AddContainerSecret(ctx context.Context, in *AddContainerSecretRequest, opts ...grpc.CallOption) (*Container, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Container)
	err := c.cc.Invoke(ctx, OrchestratorControl_AddContainerSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorControlClient) RemoveContainerSecret(ctx context.Context, in *RemoveContainerSecretRequest, opts ...grpc.CallOption) (*Container, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Container)
	err := c.cc.Invoke(ctx, OrchestratorControl_RemoveContainerSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorControlServer is the server API for OrchestratorControl service.
// All implementations must embed UnimplementedOrchestratorControlServer
// for forward compatibility.
type OrchestratorControlServer interface {
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error)
	DescribeWorkspace(context.Context, *DescribeWorkspaceRequest) (*Workspace, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	GetImage(context.Context, *GetImageRequest) (*Image, error)
	BuildImage(context.Context, *BuildImageRequest) (*Image, error)
	RebuildImage(context.Context, *RebuildImageRequest) (*Image, error)
	RebuildAllImages(context.Context, *RebuildAllImagesRequest) (*RebuildAllImagesResponse, error)
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	RebuildBaseImage(context.Context, *RebuildBaseImageRequest) (*Image, error)
	PullBaseImage(context.Context, *PullBaseImageRequest) (*Image, error)
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	StartContainer(context.Context, *StartContainerRequest) (*Container, error)
	RecreateContainer(context.Context, *RecreateContainerRequest) (*Workspace, error)
	RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerResponse, error)
	AddContainerMount(context.Context, *AddContainerMountRequest) (*Container, error)
	RemoveContainerMount(context.Context, *RemoveContainerMountRequest) (*Container, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	CreateSecret(context.Context, *CreateSecretRequest) (*Secret, error)
	WriteSecretValue(context.Context, *WriteSecretValueRequest) (*Secret, error)
	RemoveSecret(context.Context, *RemoveSecretRequest) (*RemoveSecretResponse, error)
	AddContainerSecret(context.Context, *AddContainerSecretRequest) (*Container, error)
	RemoveContainerSecret(context.Context, *RemoveContainerSecretRequest) (*Container, error)
	mustEmbedUnimplementedOrchestratorControlServer()
}

// UnimplementedOrchestratorControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorControlServer struct{}

func (UnimplementedOrchestratorControlServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedOrchestratorControlServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedOrchestratorControlServer) DescribeWorkspace(context.Context, *DescribeWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeWorkspace not implemented")
}
func (UnimplementedOrchestratorControlServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedOrchestratorControlServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedOrchestratorControlServer) GetImage(context.Context, *GetImageRequest) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedOrchestratorControlServer) BuildImage(context.Context, *BuildImageRequest) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildImage not implemented")
}
func (UnimplementedOrchestratorControlServer) RebuildImage(context.Context, *RebuildImageRequest) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildImage not implemented")
}
func (UnimplementedOrchestratorControlServer) RebuildAllImages(context.Context, *RebuildAllImagesRequest) (*RebuildAllImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildAllImages not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedOrchestratorControlServer) RebuildBaseImage(context.Context, *RebuildBaseImageRequest) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildBaseImage not implemented")
}
func (UnimplementedOrchestratorControlServer) PullBaseImage(context.Context, *PullBaseImageRequest) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method PullBaseImage not implemented")
}
func (UnimplementedOrchestratorControlServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedOrchestratorControlServer) StartContainer(context.Context, *StartContainerRequest) (*Container, error) {
	return nil, status.Error(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedOrchestratorControlServer) RecreateContainer(context.Context, *RecreateContainerRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method RecreateContainer not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveContainer not implemented")
}
func (UnimplementedOrchestratorControlServer) AddContainerMount(context.Context, *AddContainerMountRequest) (*Container, error) {
	return nil, status.Error(codes.Unimplemented, "method AddContainerMount not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveContainerMount(context.Context, *RemoveContainerMountRequest) (*Container, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveContainerMount not implemented")
}
func (UnimplementedOrchestratorControlServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedOrchestratorControlServer) CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedOrchestratorControlServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedOrchestratorControlServer) CreateSecret(context.Context, *CreateSecretRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedOrchestratorControlServer) WriteSecretValue(context.Context, *WriteSecretValueRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteSecretValue not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveSecret(context.Context, *RemoveSecretRequest) (*RemoveSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSecret not implemented")
}
func (UnimplementedOrchestratorControlServer) AddContainerSecret(context.Context, *AddContainerSecretRequest) (*Container, error) {
	return nil, status.Error(codes.Unimplemented, "method AddContainerSecret not implemented")
}
func (UnimplementedOrchestratorControlServer) RemoveContainerSecret(context.Context, *RemoveContainerSecretRequest) (*Container, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveContainerSecret not implemented")
}
func (UnimplementedOrchestratorControlServer) mustEmbedUnimplementedOrchestratorControlServer() {}
func (UnimplementedOrchestratorControlServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorControlServer will
// result in compilation errors.
type UnsafeOrchestratorControlServer interface {
	mustEmbedUnimplementedOrchestratorControlServer()
}

func RegisterOrchestratorControlServer(s grpc.ServiceRegistrar, srv OrchestratorControlServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorControl_ServiceDesc, srv)
}

func _OrchestratorControl_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_DescribeWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).DescribeWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_DescribeWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).DescribeWorkspace(ctx, req.(*DescribeWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_BuildImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).BuildImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_BuildImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).BuildImage(ctx, req.(*BuildImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RebuildImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RebuildImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RebuildImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RebuildImage(ctx, req.(*RebuildImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RebuildAllImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildAllImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RebuildAllImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RebuildAllImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RebuildAllImages(ctx, req.(*RebuildAllImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RebuildBaseImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildBaseImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RebuildBaseImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RebuildBaseImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RebuildBaseImage(ctx, req.(*RebuildBaseImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_PullBaseImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullBaseImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).PullBaseImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_PullBaseImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).PullBaseImage(ctx, req.(*PullBaseImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RecreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RecreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RecreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RecreateContainer(ctx, req.(*RecreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveContainer(ctx, req.(*RemoveContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_AddContainerMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContainerMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).AddContainerMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_AddContainerMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).AddContainerMount(ctx, req.(*AddContainerMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveContainerMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveContainerMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveContainerMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveContainerMount(ctx, req.(*RemoveContainerMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_WriteSecretValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteSecretValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).WriteSecretValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_WriteSecretValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).WriteSecretValue(ctx, req.(*WriteSecretValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveSecret(ctx, req.(*RemoveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_AddContainerSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContainerSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).AddContainerSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_AddContainerSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).AddContainerSecret(ctx, req.(*AddContainerSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorControl_RemoveContainerSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorControlServer).RemoveContainerSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorControl_RemoveContainerSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorControlServer).RemoveContainerSecret(ctx, req.(*RemoveContainerSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorControl_ServiceDesc is the grpc.ServiceDesc for OrchestratorControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dshctl.v1.OrchestratorControl",
	HandlerType: (*OrchestratorControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProjects",
			Handler:    _OrchestratorControl_ListProjects_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _OrchestratorControl_CreateWorkspace_Handler,
		},
		{
			MethodName: "DescribeWorkspace",
			Handler:    _OrchestratorControl_DescribeWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _OrchestratorControl_ListWorkspaces_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _OrchestratorControl_ListImages_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _OrchestratorControl_GetImage_Handler,
		},
		{
			MethodName: "BuildImage",
			Handler:    _OrchestratorControl_BuildImage_Handler,
		},
		{
			MethodName: "RebuildImage",
			Handler:    _OrchestratorControl_RebuildImage_Handler,
		},
		{
			MethodName: "RebuildAllImages",
			Handler:    _OrchestratorControl_RebuildAllImages_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _OrchestratorControl_RemoveImage_Handler,
		},
		{
			MethodName: "RebuildBaseImage",
			Handler:    _OrchestratorControl_RebuildBaseImage_Handler,
		},
		{
			MethodName: "PullBaseImage",
			Handler:    _OrchestratorControl_PullBaseImage_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _OrchestratorControl_ListContainers_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _OrchestratorControl_StartContainer_Handler,
		},
		{
			MethodName: "RecreateContainer",
			Handler:    _OrchestratorControl_RecreateContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _OrchestratorControl_RemoveContainer_Handler,
		},
		{
			MethodName: "AddContainerMount",
			Handler:    _OrchestratorControl_AddContainerMount_Handler,
		},
		{
			MethodName: "RemoveContainerMount",
			Handler:    _OrchestratorControl_RemoveContainerMount_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _OrchestratorControl_ListVolumes_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _OrchestratorControl_CreateVolume_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _OrchestratorControl_RemoveVolume_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _OrchestratorControl_ListSecrets_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _OrchestratorControl_CreateSecret_Handler,
		},
		{
			MethodName: "WriteSecretValue",
			Handler:    _OrchestratorControl_WriteSecretValue_Handler,
		},
		{
			MethodName: "RemoveSecret",
			Handler:    _OrchestratorControl_RemoveSecret_Handler,
		},
		{
			MethodName: "AddContainerSecret",
			Handler:    _OrchestratorControl_AddContainerSecret_Handler,
		},
		{
			MethodName: "RemoveContainerSecret",
			Handler:    _OrchestratorControl_RemoveContainerSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dshctl/v1/control.proto",
}
