// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dshctl/v1/control.proto

package dshctlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountMode int32

const (
	MountMode_MOUNT_MODE_UNSPECIFIED MountMode = 0
	MountMode_MOUNT_MODE_READ_ONLY   MountMode = 1
	MountMode_MOUNT_MODE_READ_WRITE  MountMode = 2
)

// Enum value maps for MountMode.
var (
	MountMode_name = map[int32]string{
		0: "MOUNT_MODE_UNSPECIFIED",
		1: "MOUNT_MODE_READ_ONLY",
		2: "MOUNT_MODE_READ_WRITE",
	}
	MountMode_value = map[string]int32{
		"MOUNT_MODE_UNSPECIFIED": 0,
		"MOUNT_MODE_READ_ONLY":   1,
		"MOUNT_MODE_READ_WRITE":  2,
	}
)

func (x MountMode) Enum() *MountMode {
	p := new(MountMode)
	*p = x
	return p
}

func (x MountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dshctl_v1_control_proto_enumTypes[0].Descriptor()
}

func (MountMode) Type() protoreflect.EnumType {
	return &file_dshctl_v1_control_proto_enumTypes[0]
}

func (x MountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountMode.Descriptor instead.
func (MountMode) EnumDescriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{0}
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{0}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostPath      string                 `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_dshctl_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

type ProjectMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Mode          MountMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=dshctl.v1.MountMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMount) Reset() {
	*x = ProjectMount{}
	mi := &file_dshctl_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMount) ProtoMessage() {}

func (x *ProjectMount) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMount.ProtoReflect.Descriptor instead.
func (*ProjectMount) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectMount) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectMount) GetMode() MountMode {
	if x != nil {
		return x.Mode
	}
	return MountMode_MOUNT_MODE_UNSPECIFIED
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mounts        []*ProjectMount        `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type DescribeWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeWorkspaceRequest) Reset() {
	*x = DescribeWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeWorkspaceRequest) ProtoMessage() {}

func (x *DescribeWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DescribeWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{6}
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type RecreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	Mounts        []*ProjectMount        `protobuf:"bytes,2,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecreateWorkspaceRequest) Reset() {
	*x = RecreateWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecreateWorkspaceRequest) ProtoMessage() {}

func (x *RecreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RecreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *RecreateWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *RecreateWorkspaceRequest) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type StopWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceRequest) Reset() {
	*x = StopWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceRequest) ProtoMessage() {}

func (x *StopWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StopWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *StopWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

type StopWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceResponse) Reset() {
	*x = StopWorkspaceResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceResponse) ProtoMessage() {}

func (x *StopWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*StopWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{10}
}

type Workspace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug   string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ContainerName   string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ImageId         string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mounts          []*ProjectMount        `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AgentSocketPath string                 `protobuf:"bytes,6,opt,name=agent_socket_path,json=agentSocketPath,proto3" json:"agent_socket_path,omitempty"`
	AgentToken      string                 `protobuf:"bytes,7,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_dshctl_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *Workspace) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *Workspace) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Workspace) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Workspace) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Workspace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workspace) GetAgentSocketPath() string {
	if x != nil {
		return x.AgentSocketPath
	}
	return ""
}

func (x *Workspace) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *Workspace) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{12}
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *ListImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BaseImage     string                 `protobuf:"bytes,2,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	ImageTag      string                 `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	BuiltAt       string                 `protobuf:"bytes,5,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_dshctl_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *Image) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Image) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *Image) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *Image) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *Image) GetBuiltAt() string {
	if x != nil {
		return x.BuiltAt
	}
	return ""
}

type RebuildImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BaseImage     string                 `protobuf:"bytes,2,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildImageRequest) Reset() {
	*x = RebuildImageRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildImageRequest) ProtoMessage() {}

func (x *RebuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildImageRequest.ProtoReflect.Descriptor instead.
func (*RebuildImageRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *RebuildImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RebuildImageRequest) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *RebuildImageRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_dshctl_v1_control_proto protoreflect.FileDescriptor

const file_dshctl_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17dshctl/v1/control.proto\x12\tdshctl.v1\"\x15\n" +
	"\x13ListProjectsRequest\"F\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.dshctl.v1.ProjectR\bprojects\":\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\"[\n" +
	"\fProjectMount\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12(\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x14.dshctl.v1.MountModeR\x04mode\"\x8b\x01\n" +
	"\x16CreateWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12/\n" +
	"\x06mounts\x18\x03 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\"A\n" +
	"\x18DescribeWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\"\x17\n" +
	"\x15ListWorkspacesRequest\"N\n" +
	"\x16ListWorkspacesResponse\x124\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x14.dshctl.v1.WorkspaceR\n" +
	"workspaces\"r\n" +
	"\x18RecreateWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12/\n" +
	"\x06mounts\x18\x02 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\"=\n" +
	"\x14StopWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\"\x17\n" +
	"\x15StopWorkspaceResponse\"\xa9\x02\n" +
	"\tWorkspace\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12/\n" +
	"\x06mounts\x18\x04 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x11agent_socket_path\x18\x06 \x01(\tR\x0fagentSocketPath\x12\x1f\n" +
	"\vagent_token\x18\a \x01(\tR\n" +
	"agentToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x13\n" +
	"\x11ListImagesRequest\">\n" +
	"\x12ListImagesResponse\x12(\n" +
	"\x06images\x18\x01 \x03(\v2\x10.dshctl.v1.ImageR\x06images\"\x95\x01\n" +
	"\x05Image\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x02 \x01(\tR\tbaseImage\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\x12\x1b\n" +
	"\timage_tag\x18\x04 \x01(\tR\bimageTag\x12\x19\n" +
	"\bbuilt_at\x18\x05 \x01(\tR\abuiltAt\"k\n" +
	"\x13RebuildImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x02 \x01(\tR\tbaseImage\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages*\\\n" +
	"\tMountMode\x12\x1a\n" +
	"\x16MOUNT_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MOUNT_MODE_READ_ONLY\x10\x01\x12\x19\n" +
	"\x15MOUNT_MODE_READ_WRITE\x10\x022\x8a\x05\n" +
	"\x13OrchestratorControl\x12O\n" +
	"\fListProjects\x12\x1e.dshctl.v1.ListProjectsRequest\x1a\x1f.dshctl.v1.ListProjectsResponse\x12J\n" +
	"\x0fCreateWorkspace\x12!.dshctl.v1.CreateWorkspaceRequest\x1a\x14.dshctl.v1.Workspace\x12N\n" +
	"\x11DescribeWorkspace\x12#.dshctl.v1.DescribeWorkspaceRequest\x1a\x14.dshctl.v1.Workspace\x12U\n" +
	"\x0eListWorkspaces\x12 .dshctl.v1.ListWorkspacesRequest\x1a!.dshctl.v1.ListWorkspacesResponse\x12N\n" +
	"\x11RecreateWorkspace\x12#.dshctl.v1.RecreateWorkspaceRequest\x1a\x14.dshctl.v1.Workspace\x12R\n" +
	"\rStopWorkspace\x12\x1f.dshctl.v1.StopWorkspaceRequest\x1a .dshctl.v1.StopWorkspaceResponse\x12I\n" +
	"\n" +
	"ListImages\x12\x1c.dshctl.v1.ListImagesRequest\x1a\x1d.dshctl.v1.ListImagesResponse\x12@\n" +
	"\fRebuildImage\x12\x1e.dshctl.v1.RebuildImageRequest\x1a\x10.dshctl.v1.ImageBGZEgitlab.com/Exagone313/dsh-podman/internal/genproto/dshctl/v1;dshctlv1b\x06proto3"

var (
	file_dshctl_v1_control_proto_rawDescOnce sync.Once
	file_dshctl_v1_control_proto_rawDescData []byte
)

func file_dshctl_v1_control_proto_rawDescGZIP() []byte {
	file_dshctl_v1_control_proto_rawDescOnce.Do(func() {
		file_dshctl_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dshctl_v1_control_proto_rawDesc), len(file_dshctl_v1_control_proto_rawDesc)))
	})
	return file_dshctl_v1_control_proto_rawDescData
}

var file_dshctl_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dshctl_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dshctl_v1_control_proto_goTypes = []any{
	(MountMode)(0),                   // 0: dshctl.v1.MountMode
	(*ListProjectsRequest)(nil),      // 1: dshctl.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),     // 2: dshctl.v1.ListProjectsResponse
	(*Project)(nil),                  // 3: dshctl.v1.Project
	(*ProjectMount)(nil),             // 4: dshctl.v1.ProjectMount
	(*CreateWorkspaceRequest)(nil),   // 5: dshctl.v1.CreateWorkspaceRequest
	(*DescribeWorkspaceRequest)(nil), // 6: dshctl.v1.DescribeWorkspaceRequest
	(*ListWorkspacesRequest)(nil),    // 7: dshctl.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),   // 8: dshctl.v1.ListWorkspacesResponse
	(*RecreateWorkspaceRequest)(nil), // 9: dshctl.v1.RecreateWorkspaceRequest
	(*StopWorkspaceRequest)(nil),     // 10: dshctl.v1.StopWorkspaceRequest
	(*StopWorkspaceResponse)(nil),    // 11: dshctl.v1.StopWorkspaceResponse
	(*Workspace)(nil),                // 12: dshctl.v1.Workspace
	(*ListImagesRequest)(nil),        // 13: dshctl.v1.ListImagesRequest
	(*ListImagesResponse)(nil),       // 14: dshctl.v1.ListImagesResponse
	(*Image)(nil),                    // 15: dshctl.v1.Image
	(*RebuildImageRequest)(nil),      // 16: dshctl.v1.RebuildImageRequest
}
var file_dshctl_v1_control_proto_depIdxs = []int32{
	3,  // 0: dshctl.v1.ListProjectsResponse.projects:type_name -> dshctl.v1.Project
	0,  // 1: dshctl.v1.ProjectMount.mode:type_name -> dshctl.v1.MountMode
	4,  // 2: dshctl.v1.CreateWorkspaceRequest.mounts:type_name -> dshctl.v1.ProjectMount
	12, // 3: dshctl.v1.ListWorkspacesResponse.workspaces:type_name -> dshctl.v1.Workspace
	4,  // 4: dshctl.v1.RecreateWorkspaceRequest.mounts:type_name -> dshctl.v1.ProjectMount
	4,  // 5: dshctl.v1.Workspace.mounts:type_name -> dshctl.v1.ProjectMount
	15, // 6: dshctl.v1.ListImagesResponse.images:type_name -> dshctl.v1.Image
	1,  // 7: dshctl.v1.OrchestratorControl.ListProjects:input_type -> dshctl.v1.ListProjectsRequest
	5,  // 8: dshctl.v1.OrchestratorControl.CreateWorkspace:input_type -> dshctl.v1.CreateWorkspaceRequest
	6,  // 9: dshctl.v1.OrchestratorControl.DescribeWorkspace:input_type -> dshctl.v1.DescribeWorkspaceRequest
	7,  // 10: dshctl.v1.OrchestratorControl.ListWorkspaces:input_type -> dshctl.v1.ListWorkspacesRequest
	9,  // 11: dshctl.v1.OrchestratorControl.RecreateWorkspace:input_type -> dshctl.v1.RecreateWorkspaceRequest
	10, // 12: dshctl.v1.OrchestratorControl.StopWorkspace:input_type -> dshctl.v1.StopWorkspaceRequest
	13, // 13: dshctl.v1.OrchestratorControl.ListImages:input_type -> dshctl.v1.ListImagesRequest
	16, // 14: dshctl.v1.OrchestratorControl.RebuildImage:input_type -> dshctl.v1.RebuildImageRequest
	2,  // 15: dshctl.v1.OrchestratorControl.ListProjects:output_type -> dshctl.v1.ListProjectsResponse
	12, // 16: dshctl.v1.OrchestratorControl.CreateWorkspace:output_type -> dshctl.v1.Workspace
	12, // 17: dshctl.v1.OrchestratorControl.DescribeWorkspace:output_type -> dshctl.v1.Workspace
	8,  // 18: dshctl.v1.OrchestratorControl.ListWorkspaces:output_type -> dshctl.v1.ListWorkspacesResponse
	12, // 19: dshctl.v1.OrchestratorControl.RecreateWorkspace:output_type -> dshctl.v1.Workspace
	11, // 20: dshctl.v1.OrchestratorControl.StopWorkspace:output_type -> dshctl.v1.StopWorkspaceResponse
	14, // 21: dshctl.v1.OrchestratorControl.ListImages:output_type -> dshctl.v1.ListImagesResponse
	15, // 22: dshctl.v1.OrchestratorControl.RebuildImage:output_type -> dshctl.v1.Image
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dshctl_v1_control_proto_init() }
func file_dshctl_v1_control_proto_init() {
	if File_dshctl_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dshctl_v1_control_proto_rawDesc), len(file_dshctl_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dshctl_v1_control_proto_goTypes,
		DependencyIndexes: file_dshctl_v1_control_proto_depIdxs,
		EnumInfos:         file_dshctl_v1_control_proto_enumTypes,
		MessageInfos:      file_dshctl_v1_control_proto_msgTypes,
	}.Build()
	File_dshctl_v1_control_proto = out.File
	file_dshctl_v1_control_proto_goTypes = nil
	file_dshctl_v1_control_proto_depIdxs = nil
}
