// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dshctl/v1/control.proto

package dshctlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountMode int32

const (
	MountMode_MOUNT_MODE_UNSPECIFIED MountMode = 0
	MountMode_MOUNT_MODE_READ_ONLY   MountMode = 1
	MountMode_MOUNT_MODE_READ_WRITE  MountMode = 2
)

// Enum value maps for MountMode.
var (
	MountMode_name = map[int32]string{
		0: "MOUNT_MODE_UNSPECIFIED",
		1: "MOUNT_MODE_READ_ONLY",
		2: "MOUNT_MODE_READ_WRITE",
	}
	MountMode_value = map[string]int32{
		"MOUNT_MODE_UNSPECIFIED": 0,
		"MOUNT_MODE_READ_ONLY":   1,
		"MOUNT_MODE_READ_WRITE":  2,
	}
)

func (x MountMode) Enum() *MountMode {
	p := new(MountMode)
	*p = x
	return p
}

func (x MountMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountMode) Descriptor() protoreflect.EnumDescriptor {
	return file_dshctl_v1_control_proto_enumTypes[0].Descriptor()
}

func (MountMode) Type() protoreflect.EnumType {
	return &file_dshctl_v1_control_proto_enumTypes[0]
}

func (x MountMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountMode.Descriptor instead.
func (MountMode) EnumDescriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{0}
}

type MountKind int32

const (
	MountKind_MOUNT_KIND_UNSPECIFIED MountKind = 0
	MountKind_MOUNT_KIND_PROJECT     MountKind = 1
	MountKind_MOUNT_KIND_TMPFS       MountKind = 2
	MountKind_MOUNT_KIND_VOLUME      MountKind = 3
)

// Enum value maps for MountKind.
var (
	MountKind_name = map[int32]string{
		0: "MOUNT_KIND_UNSPECIFIED",
		1: "MOUNT_KIND_PROJECT",
		2: "MOUNT_KIND_TMPFS",
		3: "MOUNT_KIND_VOLUME",
	}
	MountKind_value = map[string]int32{
		"MOUNT_KIND_UNSPECIFIED": 0,
		"MOUNT_KIND_PROJECT":     1,
		"MOUNT_KIND_TMPFS":       2,
		"MOUNT_KIND_VOLUME":      3,
	}
)

func (x MountKind) Enum() *MountKind {
	p := new(MountKind)
	*p = x
	return p
}

func (x MountKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MountKind) Descriptor() protoreflect.EnumDescriptor {
	return file_dshctl_v1_control_proto_enumTypes[1].Descriptor()
}

func (MountKind) Type() protoreflect.EnumType {
	return &file_dshctl_v1_control_proto_enumTypes[1]
}

func (x MountKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MountKind.Descriptor instead.
func (MountKind) EnumDescriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{1}
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{0}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostPath      string                 `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_dshctl_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

type ProjectMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Mode          MountMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=dshctl.v1.MountMode" json:"mode,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Kind          MountKind              `protobuf:"varint,5,opt,name=kind,proto3,enum=dshctl.v1.MountKind" json:"kind,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMount) Reset() {
	*x = ProjectMount{}
	mi := &file_dshctl_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMount) ProtoMessage() {}

func (x *ProjectMount) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMount.ProtoReflect.Descriptor instead.
func (*ProjectMount) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectMount) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectMount) GetMode() MountMode {
	if x != nil {
		return x.Mode
	}
	return MountMode_MOUNT_MODE_UNSPECIFIED
}

func (x *ProjectMount) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProjectMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ProjectMount) GetKind() MountKind {
	if x != nil {
		return x.Kind
	}
	return MountKind_MOUNT_KIND_UNSPECIFIED
}

func (x *ProjectMount) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mounts        []*ProjectMount        `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type DescribeWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeWorkspaceRequest) Reset() {
	*x = DescribeWorkspaceRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeWorkspaceRequest) ProtoMessage() {}

func (x *DescribeWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DescribeWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeWorkspaceRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{6}
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type Workspace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug   string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ContainerName   string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ImageId         string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mounts          []*ProjectMount        `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AgentSocketPath string                 `protobuf:"bytes,6,opt,name=agent_socket_path,json=agentSocketPath,proto3" json:"agent_socket_path,omitempty"`
	AgentToken      string                 `protobuf:"bytes,7,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_dshctl_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Workspace) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *Workspace) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Workspace) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Workspace) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Workspace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workspace) GetAgentSocketPath() string {
	if x != nil {
		return x.AgentSocketPath
	}
	return ""
}

func (x *Workspace) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *Workspace) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{9}
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *ListImagesResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BaseImage     string                 `protobuf:"bytes,2,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	ImageTag      string                 `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	BuiltAt       string                 `protobuf:"bytes,5,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_dshctl_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *Image) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Image) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *Image) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *Image) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *Image) GetBuiltAt() string {
	if x != nil {
		return x.BuiltAt
	}
	return ""
}

type RebuildImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BaseImage     string                 `protobuf:"bytes,2,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildImageRequest) Reset() {
	*x = RebuildImageRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildImageRequest) ProtoMessage() {}

func (x *RebuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildImageRequest.ProtoReflect.Descriptor instead.
func (*RebuildImageRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *RebuildImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RebuildImageRequest) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *RebuildImageRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type RemoveImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{14}
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *GetImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type BuildImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BaseImage     string                 `protobuf:"bytes,2,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildImageRequest) Reset() {
	*x = BuildImageRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildImageRequest) ProtoMessage() {}

func (x *BuildImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildImageRequest.ProtoReflect.Descriptor instead.
func (*BuildImageRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *BuildImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *BuildImageRequest) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *BuildImageRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{17}
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *ListContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerName   string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	WorkspaceSlug   string                 `protobuf:"bytes,2,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ImageId         string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Mounts          []*ProjectMount        `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	PodmanName      string                 `protobuf:"bytes,7,opt,name=podman_name,json=podmanName,proto3" json:"podman_name,omitempty"`
	AgentSocketPath string                 `protobuf:"bytes,8,opt,name=agent_socket_path,json=agentSocketPath,proto3" json:"agent_socket_path,omitempty"`
	AgentToken      string                 `protobuf:"bytes,9,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_dshctl_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *Container) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Container) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *Container) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Container) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Container) GetPodmanName() string {
	if x != nil {
		return x.PodmanName
	}
	return ""
}

func (x *Container) GetAgentSocketPath() string {
	if x != nil {
		return x.AgentSocketPath
	}
	return ""
}

func (x *Container) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mounts        []*ProjectMount        `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *StartContainerRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *StartContainerRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *StartContainerRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *StartContainerRequest) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type RecreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	Mounts        []*ProjectMount        `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecreateContainerRequest) Reset() {
	*x = RecreateContainerRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecreateContainerRequest) ProtoMessage() {}

func (x *RecreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecreateContainerRequest.ProtoReflect.Descriptor instead.
func (*RecreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *RecreateContainerRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *RecreateContainerRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *RecreateContainerRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *RecreateContainerRequest) GetMounts() []*ProjectMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type RemoveContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveContainerRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *RemoveContainerRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type RemoveContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerResponse) Reset() {
	*x = RemoveContainerResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerResponse) ProtoMessage() {}

func (x *RemoveContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerResponse.ProtoReflect.Descriptor instead.
func (*RemoveContainerResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{23}
}

type AddContainerMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Mode          MountMode              `protobuf:"varint,6,opt,name=mode,proto3,enum=dshctl.v1.MountMode" json:"mode,omitempty"`
	Kind          MountKind              `protobuf:"varint,7,opt,name=kind,proto3,enum=dshctl.v1.MountKind" json:"kind,omitempty"`
	Volume        string                 `protobuf:"bytes,8,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContainerMountRequest) Reset() {
	*x = AddContainerMountRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContainerMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContainerMountRequest) ProtoMessage() {}

func (x *AddContainerMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContainerMountRequest.ProtoReflect.Descriptor instead.
func (*AddContainerMountRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *AddContainerMountRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *AddContainerMountRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *AddContainerMountRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AddContainerMountRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddContainerMountRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *AddContainerMountRequest) GetMode() MountMode {
	if x != nil {
		return x.Mode
	}
	return MountMode_MOUNT_MODE_UNSPECIFIED
}

func (x *AddContainerMountRequest) GetKind() MountKind {
	if x != nil {
		return x.Kind
	}
	return MountKind_MOUNT_KIND_UNSPECIFIED
}

func (x *AddContainerMountRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type RemoveContainerMountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceSlug string                 `protobuf:"bytes,1,opt,name=workspace_slug,json=workspaceSlug,proto3" json:"workspace_slug,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Kind          MountKind              `protobuf:"varint,5,opt,name=kind,proto3,enum=dshctl.v1.MountKind" json:"kind,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Destination   string                 `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerMountRequest) Reset() {
	*x = RemoveContainerMountRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerMountRequest) ProtoMessage() {}

func (x *RemoveContainerMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerMountRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerMountRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveContainerMountRequest) GetWorkspaceSlug() string {
	if x != nil {
		return x.WorkspaceSlug
	}
	return ""
}

func (x *RemoveContainerMountRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *RemoveContainerMountRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RemoveContainerMountRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveContainerMountRequest) GetKind() MountKind {
	if x != nil {
		return x.Kind
	}
	return MountKind_MOUNT_KIND_UNSPECIFIED
}

func (x *RemoveContainerMountRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *RemoveContainerMountRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{26}
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *ListVolumesResponse) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_dshctl_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{29}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeRequest) Reset() {
	*x = RemoveVolumeRequest{}
	mi := &file_dshctl_v1_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeRequest) ProtoMessage() {}

func (x *RemoveVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeRequest.ProtoReflect.Descriptor instead.
func (*RemoveVolumeRequest) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeResponse) Reset() {
	*x = RemoveVolumeResponse{}
	mi := &file_dshctl_v1_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeResponse) ProtoMessage() {}

func (x *RemoveVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshctl_v1_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeResponse.ProtoReflect.Descriptor instead.
func (*RemoveVolumeResponse) Descriptor() ([]byte, []int) {
	return file_dshctl_v1_control_proto_rawDescGZIP(), []int{31}
}

var File_dshctl_v1_control_proto protoreflect.FileDescriptor

const file_dshctl_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17dshctl/v1/control.proto\x12\tdshctl.v1\"\x15\n" +
	"\x13ListProjectsRequest\"F\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.dshctl.v1.ProjectR\bprojects\":\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\"\xd3\x01\n" +
	"\fProjectMount\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12(\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x14.dshctl.v1.MountModeR\x04mode\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12(\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x14.dshctl.v1.MountKindR\x04kind\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\"\x8b\x01\n" +
	"\x16CreateWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12/\n" +
	"\x06mounts\x18\x03 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\"A\n" +
	"\x18DescribeWorkspaceRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\"\x17\n" +
	"\x15ListWorkspacesRequest\"N\n" +
	"\x16ListWorkspacesResponse\x124\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x14.dshctl.v1.WorkspaceR\n" +
	"workspaces\"\xa9\x02\n" +
	"\tWorkspace\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12/\n" +
	"\x06mounts\x18\x04 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x11agent_socket_path\x18\x06 \x01(\tR\x0fagentSocketPath\x12\x1f\n" +
	"\vagent_token\x18\a \x01(\tR\n" +
	"agentToken\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x13\n" +
	"\x11ListImagesRequest\">\n" +
	"\x12ListImagesResponse\x12(\n" +
	"\x06images\x18\x01 \x03(\v2\x10.dshctl.v1.ImageR\x06images\"\x95\x01\n" +
	"\x05Image\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x02 \x01(\tR\tbaseImage\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\x12\x1b\n" +
	"\timage_tag\x18\x04 \x01(\tR\bimageTag\x12\x19\n" +
	"\bbuilt_at\x18\x05 \x01(\tR\abuiltAt\"k\n" +
	"\x13RebuildImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x02 \x01(\tR\tbaseImage\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\"/\n" +
	"\x12RemoveImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"\x15\n" +
	"\x13RemoveImageResponse\",\n" +
	"\x0fGetImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"i\n" +
	"\x11BuildImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x02 \x01(\tR\tbaseImage\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\"\x17\n" +
	"\x15ListContainersRequest\"N\n" +
	"\x16ListContainersResponse\x124\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x14.dshctl.v1.ContainerR\n" +
	"containers\"\xca\x02\n" +
	"\tContainer\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12%\n" +
	"\x0eworkspace_slug\x18\x02 \x01(\tR\rworkspaceSlug\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12/\n" +
	"\x06mounts\x18\x06 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\x12\x1f\n" +
	"\vpodman_name\x18\a \x01(\tR\n" +
	"podmanName\x12*\n" +
	"\x11agent_socket_path\x18\b \x01(\tR\x0fagentSocketPath\x12\x1f\n" +
	"\vagent_token\x18\t \x01(\tR\n" +
	"agentToken\"\xa8\x01\n" +
	"\x15StartContainerRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12/\n" +
	"\x06mounts\x18\x04 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\"\xab\x01\n" +
	"\x18RecreateContainerRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12/\n" +
	"\x06mounts\x18\x04 \x03(\v2\x17.dshctl.v1.ProjectMountR\x06mounts\"]\n" +
	"\x16RemoveContainerRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\"\x19\n" +
	"\x17RemoveContainerResponse\"\x9b\x02\n" +
	"\x18AddContainerMountRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12(\n" +
	"\x04mode\x18\x06 \x01(\x0e2\x14.dshctl.v1.MountModeR\x04mode\x12(\n" +
	"\x04kind\x18\a \x01(\x0e2\x14.dshctl.v1.MountKindR\x04kind\x12\x16\n" +
	"\x06volume\x18\b \x01(\tR\x06volume\"\xf4\x01\n" +
	"\x1bRemoveContainerMountRequest\x12%\n" +
	"\x0eworkspace_slug\x18\x01 \x01(\tR\rworkspaceSlug\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12(\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x14.dshctl.v1.MountKindR\x04kind\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\x12 \n" +
	"\vdestination\x18\a \x01(\tR\vdestination\"\x14\n" +
	"\x12ListVolumesRequest\"B\n" +
	"\x13ListVolumesResponse\x12+\n" +
	"\avolumes\x18\x01 \x03(\v2\x11.dshctl.v1.VolumeR\avolumes\"\x1c\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13RemoveVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14RemoveVolumeResponse*\\\n" +
	"\tMountMode\x12\x1a\n" +
	"\x16MOUNT_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MOUNT_MODE_READ_ONLY\x10\x01\x12\x19\n" +
	"\x15MOUNT_MODE_READ_WRITE\x10\x02*l\n" +
	"\tMountKind\x12\x1a\n" +
	"\x16MOUNT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MOUNT_KIND_PROJECT\x10\x01\x12\x14\n" +
	"\x10MOUNT_KIND_TMPFS\x10\x02\x12\x15\n" +
	"\x11MOUNT_KIND_VOLUME\x10\x032\xff\n" +
	"\n" +
	"\x13OrchestratorControl\x12O\n" +
	"\fListProjects\x12\x1e.dshctl.v1.ListProjectsRequest\x1a\x1f.dshctl.v1.ListProjectsResponse\x12J\n" +
	"\x0fCreateWorkspace\x12!.dshctl.v1.CreateWorkspaceRequest\x1a\x14.dshctl.v1.Workspace\x12N\n" +
	"\x11DescribeWorkspace\x12#.dshctl.v1.DescribeWorkspaceRequest\x1a\x14.dshctl.v1.Workspace\x12U\n" +
	"\x0eListWorkspaces\x12 .dshctl.v1.ListWorkspacesRequest\x1a!.dshctl.v1.ListWorkspacesResponse\x12I\n" +
	"\n" +
	"ListImages\x12\x1c.dshctl.v1.ListImagesRequest\x1a\x1d.dshctl.v1.ListImagesResponse\x128\n" +
	"\bGetImage\x12\x1a.dshctl.v1.GetImageRequest\x1a\x10.dshctl.v1.Image\x12<\n" +
	"\n" +
	"BuildImage\x12\x1c.dshctl.v1.BuildImageRequest\x1a\x10.dshctl.v1.Image\x12@\n" +
	"\fRebuildImage\x12\x1e.dshctl.v1.RebuildImageRequest\x1a\x10.dshctl.v1.Image\x12L\n" +
	"\vRemoveImage\x12\x1d.dshctl.v1.RemoveImageRequest\x1a\x1e.dshctl.v1.RemoveImageResponse\x12U\n" +
	"\x0eListContainers\x12 .dshctl.v1.ListContainersRequest\x1a!.dshctl.v1.ListContainersResponse\x12H\n" +
	"\x0eStartContainer\x12 .dshctl.v1.StartContainerRequest\x1a\x14.dshctl.v1.Container\x12N\n" +
	"\x11RecreateContainer\x12#.dshctl.v1.RecreateContainerRequest\x1a\x14.dshctl.v1.Workspace\x12X\n" +
	"\x0fRemoveContainer\x12!.dshctl.v1.RemoveContainerRequest\x1a\".dshctl.v1.RemoveContainerResponse\x12N\n" +
	"\x11AddContainerMount\x12#.dshctl.v1.AddContainerMountRequest\x1a\x14.dshctl.v1.Container\x12T\n" +
	"\x14RemoveContainerMount\x12&.dshctl.v1.RemoveContainerMountRequest\x1a\x14.dshctl.v1.Container\x12L\n" +
	"\vListVolumes\x12\x1d.dshctl.v1.ListVolumesRequest\x1a\x1e.dshctl.v1.ListVolumesResponse\x12A\n" +
	"\fCreateVolume\x12\x1e.dshctl.v1.CreateVolumeRequest\x1a\x11.dshctl.v1.Volume\x12O\n" +
	"\fRemoveVolume\x12\x1e.dshctl.v1.RemoveVolumeRequest\x1a\x1f.dshctl.v1.RemoveVolumeResponseBGZEgitlab.com/Exagone313/dsh-podman/internal/genproto/dshctl/v1;dshctlv1b\x06proto3"

var (
	file_dshctl_v1_control_proto_rawDescOnce sync.Once
	file_dshctl_v1_control_proto_rawDescData []byte
)

func file_dshctl_v1_control_proto_rawDescGZIP() []byte {
	file_dshctl_v1_control_proto_rawDescOnce.Do(func() {
		file_dshctl_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dshctl_v1_control_proto_rawDesc), len(file_dshctl_v1_control_proto_rawDesc)))
	})
	return file_dshctl_v1_control_proto_rawDescData
}

var file_dshctl_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dshctl_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_dshctl_v1_control_proto_goTypes = []any{
	(MountMode)(0),                      // 0: dshctl.v1.MountMode
	(MountKind)(0),                      // 1: dshctl.v1.MountKind
	(*ListProjectsRequest)(nil),         // 2: dshctl.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),        // 3: dshctl.v1.ListProjectsResponse
	(*Project)(nil),                     // 4: dshctl.v1.Project
	(*ProjectMount)(nil),                // 5: dshctl.v1.ProjectMount
	(*CreateWorkspaceRequest)(nil),      // 6: dshctl.v1.CreateWorkspaceRequest
	(*DescribeWorkspaceRequest)(nil),    // 7: dshctl.v1.DescribeWorkspaceRequest
	(*ListWorkspacesRequest)(nil),       // 8: dshctl.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),      // 9: dshctl.v1.ListWorkspacesResponse
	(*Workspace)(nil),                   // 10: dshctl.v1.Workspace
	(*ListImagesRequest)(nil),           // 11: dshctl.v1.ListImagesRequest
	(*ListImagesResponse)(nil),          // 12: dshctl.v1.ListImagesResponse
	(*Image)(nil),                       // 13: dshctl.v1.Image
	(*RebuildImageRequest)(nil),         // 14: dshctl.v1.RebuildImageRequest
	(*RemoveImageRequest)(nil),          // 15: dshctl.v1.RemoveImageRequest
	(*RemoveImageResponse)(nil),         // 16: dshctl.v1.RemoveImageResponse
	(*GetImageRequest)(nil),             // 17: dshctl.v1.GetImageRequest
	(*BuildImageRequest)(nil),           // 18: dshctl.v1.BuildImageRequest
	(*ListContainersRequest)(nil),       // 19: dshctl.v1.ListContainersRequest
	(*ListContainersResponse)(nil),      // 20: dshctl.v1.ListContainersResponse
	(*Container)(nil),                   // 21: dshctl.v1.Container
	(*StartContainerRequest)(nil),       // 22: dshctl.v1.StartContainerRequest
	(*RecreateContainerRequest)(nil),    // 23: dshctl.v1.RecreateContainerRequest
	(*RemoveContainerRequest)(nil),      // 24: dshctl.v1.RemoveContainerRequest
	(*RemoveContainerResponse)(nil),     // 25: dshctl.v1.RemoveContainerResponse
	(*AddContainerMountRequest)(nil),    // 26: dshctl.v1.AddContainerMountRequest
	(*RemoveContainerMountRequest)(nil), // 27: dshctl.v1.RemoveContainerMountRequest
	(*ListVolumesRequest)(nil),          // 28: dshctl.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),         // 29: dshctl.v1.ListVolumesResponse
	(*Volume)(nil),                      // 30: dshctl.v1.Volume
	(*CreateVolumeRequest)(nil),         // 31: dshctl.v1.CreateVolumeRequest
	(*RemoveVolumeRequest)(nil),         // 32: dshctl.v1.RemoveVolumeRequest
	(*RemoveVolumeResponse)(nil),        // 33: dshctl.v1.RemoveVolumeResponse
}
var file_dshctl_v1_control_proto_depIdxs = []int32{
	4,  // 0: dshctl.v1.ListProjectsResponse.projects:type_name -> dshctl.v1.Project
	0,  // 1: dshctl.v1.ProjectMount.mode:type_name -> dshctl.v1.MountMode
	1,  // 2: dshctl.v1.ProjectMount.kind:type_name -> dshctl.v1.MountKind
	5,  // 3: dshctl.v1.CreateWorkspaceRequest.mounts:type_name -> dshctl.v1.ProjectMount
	10, // 4: dshctl.v1.ListWorkspacesResponse.workspaces:type_name -> dshctl.v1.Workspace
	5,  // 5: dshctl.v1.Workspace.mounts:type_name -> dshctl.v1.ProjectMount
	13, // 6: dshctl.v1.ListImagesResponse.images:type_name -> dshctl.v1.Image
	21, // 7: dshctl.v1.ListContainersResponse.containers:type_name -> dshctl.v1.Container
	5,  // 8: dshctl.v1.Container.mounts:type_name -> dshctl.v1.ProjectMount
	5,  // 9: dshctl.v1.StartContainerRequest.mounts:type_name -> dshctl.v1.ProjectMount
	5,  // 10: dshctl.v1.RecreateContainerRequest.mounts:type_name -> dshctl.v1.ProjectMount
	0,  // 11: dshctl.v1.AddContainerMountRequest.mode:type_name -> dshctl.v1.MountMode
	1,  // 12: dshctl.v1.AddContainerMountRequest.kind:type_name -> dshctl.v1.MountKind
	1,  // 13: dshctl.v1.RemoveContainerMountRequest.kind:type_name -> dshctl.v1.MountKind
	30, // 14: dshctl.v1.ListVolumesResponse.volumes:type_name -> dshctl.v1.Volume
	2,  // 15: dshctl.v1.OrchestratorControl.ListProjects:input_type -> dshctl.v1.ListProjectsRequest
	6,  // 16: dshctl.v1.OrchestratorControl.CreateWorkspace:input_type -> dshctl.v1.CreateWorkspaceRequest
	7,  // 17: dshctl.v1.OrchestratorControl.DescribeWorkspace:input_type -> dshctl.v1.DescribeWorkspaceRequest
	8,  // 18: dshctl.v1.OrchestratorControl.ListWorkspaces:input_type -> dshctl.v1.ListWorkspacesRequest
	11, // 19: dshctl.v1.OrchestratorControl.ListImages:input_type -> dshctl.v1.ListImagesRequest
	17, // 20: dshctl.v1.OrchestratorControl.GetImage:input_type -> dshctl.v1.GetImageRequest
	18, // 21: dshctl.v1.OrchestratorControl.BuildImage:input_type -> dshctl.v1.BuildImageRequest
	14, // 22: dshctl.v1.OrchestratorControl.RebuildImage:input_type -> dshctl.v1.RebuildImageRequest
	15, // 23: dshctl.v1.OrchestratorControl.RemoveImage:input_type -> dshctl.v1.RemoveImageRequest
	19, // 24: dshctl.v1.OrchestratorControl.ListContainers:input_type -> dshctl.v1.ListContainersRequest
	22, // 25: dshctl.v1.OrchestratorControl.StartContainer:input_type -> dshctl.v1.StartContainerRequest
	23, // 26: dshctl.v1.OrchestratorControl.RecreateContainer:input_type -> dshctl.v1.RecreateContainerRequest
	24, // 27: dshctl.v1.OrchestratorControl.RemoveContainer:input_type -> dshctl.v1.RemoveContainerRequest
	26, // 28: dshctl.v1.OrchestratorControl.AddContainerMount:input_type -> dshctl.v1.AddContainerMountRequest
	27, // 29: dshctl.v1.OrchestratorControl.RemoveContainerMount:input_type -> dshctl.v1.RemoveContainerMountRequest
	28, // 30: dshctl.v1.OrchestratorControl.ListVolumes:input_type -> dshctl.v1.ListVolumesRequest
	31, // 31: dshctl.v1.OrchestratorControl.CreateVolume:input_type -> dshctl.v1.CreateVolumeRequest
	32, // 32: dshctl.v1.OrchestratorControl.RemoveVolume:input_type -> dshctl.v1.RemoveVolumeRequest
	3,  // 33: dshctl.v1.OrchestratorControl.ListProjects:output_type -> dshctl.v1.ListProjectsResponse
	10, // 34: dshctl.v1.OrchestratorControl.CreateWorkspace:output_type -> dshctl.v1.Workspace
	10, // 35: dshctl.v1.OrchestratorControl.DescribeWorkspace:output_type -> dshctl.v1.Workspace
	9,  // 36: dshctl.v1.OrchestratorControl.ListWorkspaces:output_type -> dshctl.v1.ListWorkspacesResponse
	12, // 37: dshctl.v1.OrchestratorControl.ListImages:output_type -> dshctl.v1.ListImagesResponse
	13, // 38: dshctl.v1.OrchestratorControl.GetImage:output_type -> dshctl.v1.Image
	13, // 39: dshctl.v1.OrchestratorControl.BuildImage:output_type -> dshctl.v1.Image
	13, // 40: dshctl.v1.OrchestratorControl.RebuildImage:output_type -> dshctl.v1.Image
	16, // 41: dshctl.v1.OrchestratorControl.RemoveImage:output_type -> dshctl.v1.RemoveImageResponse
	20, // 42: dshctl.v1.OrchestratorControl.ListContainers:output_type -> dshctl.v1.ListContainersResponse
	21, // 43: dshctl.v1.OrchestratorControl.StartContainer:output_type -> dshctl.v1.Container
	10, // 44: dshctl.v1.OrchestratorControl.RecreateContainer:output_type -> dshctl.v1.Workspace
	25, // 45: dshctl.v1.OrchestratorControl.RemoveContainer:output_type -> dshctl.v1.RemoveContainerResponse
	21, // 46: dshctl.v1.OrchestratorControl.AddContainerMount:output_type -> dshctl.v1.Container
	21, // 47: dshctl.v1.OrchestratorControl.RemoveContainerMount:output_type -> dshctl.v1.Container
	29, // 48: dshctl.v1.OrchestratorControl.ListVolumes:output_type -> dshctl.v1.ListVolumesResponse
	30, // 49: dshctl.v1.OrchestratorControl.CreateVolume:output_type -> dshctl.v1.Volume
	33, // 50: dshctl.v1.OrchestratorControl.RemoveVolume:output_type -> dshctl.v1.RemoveVolumeResponse
	33, // [33:51] is the sub-list for method output_type
	15, // [15:33] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_dshctl_v1_control_proto_init() }
func file_dshctl_v1_control_proto_init() {
	if File_dshctl_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dshctl_v1_control_proto_rawDesc), len(file_dshctl_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dshctl_v1_control_proto_goTypes,
		DependencyIndexes: file_dshctl_v1_control_proto_depIdxs,
		EnumInfos:         file_dshctl_v1_control_proto_enumTypes,
		MessageInfos:      file_dshctl_v1_control_proto_msgTypes,
	}.Build()
	File_dshctl_v1_control_proto = out.File
	file_dshctl_v1_control_proto_goTypes = nil
	file_dshctl_v1_control_proto_depIdxs = nil
}
