// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dshguest/v1/guest.proto

package dshguestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecInput_Start
	//	*ExecInput_StdinChunk
	Payload       isExecInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{0}
}

func (x *ExecInput) GetPayload() isExecInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecInput) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Payload.(*ExecInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecInput) GetStdinChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecInput_StdinChunk); ok {
			return x.StdinChunk
		}
	}
	return nil
}

type isExecInput_Payload interface {
	isExecInput_Payload()
}

type ExecInput_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecInput_StdinChunk struct {
	StdinChunk []byte `protobuf:"bytes,2,opt,name=stdin_chunk,json=stdinChunk,proto3,oneof"`
}

func (*ExecInput_Start) isExecInput_Payload() {}

func (*ExecInput_StdinChunk) isExecInput_Payload() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argv          []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecOutput_StdoutChunk
	//	*ExecOutput_StderrChunk
	//	*ExecOutput_Exit
	Payload       isExecOutput_Payload `protobuf_oneof:"payload"`
	ProcessId     string               `protobuf:"bytes,4,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *ExecOutput) GetPayload() isExecOutput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecOutput) GetStdoutChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_StdoutChunk); ok {
			return x.StdoutChunk
		}
	}
	return nil
}

func (x *ExecOutput) GetStderrChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_StderrChunk); ok {
			return x.StderrChunk
		}
	}
	return nil
}

func (x *ExecOutput) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ExecOutput) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type isExecOutput_Payload interface {
	isExecOutput_Payload()
}

type ExecOutput_StdoutChunk struct {
	StdoutChunk []byte `protobuf:"bytes,1,opt,name=stdout_chunk,json=stdoutChunk,proto3,oneof"`
}

type ExecOutput_StderrChunk struct {
	StderrChunk []byte `protobuf:"bytes,2,opt,name=stderr_chunk,json=stderrChunk,proto3,oneof"`
}

type ExecOutput_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOutput_StdoutChunk) isExecOutput_Payload() {}

func (*ExecOutput_StderrChunk) isExecOutput_Payload() {}

func (*ExecOutput_Exit) isExecOutput_Payload() {}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signaled      bool                   `protobuf:"varint,2,opt,name=signaled,proto3" json:"signaled,omitempty"`
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecExit) GetSignaled() bool {
	if x != nil {
		return x.Signaled
	}
	return false
}

func (x *ExecExit) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *SignalRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *SignalRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{5}
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileChunk) Reset() {
	*x = ReadFileChunk{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileChunk) ProtoMessage() {}

func (x *ReadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileChunk.ProtoReflect.Descriptor instead.
func (*ReadFileChunk) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteFileChunk_Start
	//	*WriteFileChunk_DataChunk
	Payload       isWriteFileChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileChunk) Reset() {
	*x = WriteFileChunk{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileChunk) ProtoMessage() {}

func (x *WriteFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileChunk.ProtoReflect.Descriptor instead.
func (*WriteFileChunk) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *WriteFileChunk) GetPayload() isWriteFileChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteFileChunk) GetStart() *WriteFileStart {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileChunk_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *WriteFileChunk) GetDataChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileChunk_DataChunk); ok {
			return x.DataChunk
		}
	}
	return nil
}

type isWriteFileChunk_Payload interface {
	isWriteFileChunk_Payload()
}

type WriteFileChunk_Start struct {
	Start *WriteFileStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type WriteFileChunk_DataChunk struct {
	DataChunk []byte `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3,oneof"`
}

func (*WriteFileChunk_Start) isWriteFileChunk_Payload() {}

func (*WriteFileChunk_DataChunk) isWriteFileChunk_Payload() {}

type WriteFileStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Create        bool                   `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	Truncate      bool                   `protobuf:"varint,3,opt,name=truncate,proto3" json:"truncate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileStart) Reset() {
	*x = WriteFileStart{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileStart) ProtoMessage() {}

func (x *WriteFileStart) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileStart.ProtoReflect.Descriptor instead.
func (*WriteFileStart) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *WriteFileStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileStart) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *WriteFileStart) GetTruncate() bool {
	if x != nil {
		return x.Truncate
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModifiedAt    string                 `protobuf:"bytes,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{12}
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatResponse) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{13}
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{14}
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{15}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Parents       bool                   `protobuf:"varint,2,opt,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{16}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{17}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{19}
}

type StartDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uid           *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=gid,proto3" json:"gid,omitempty"`
	Groups        []uint32               `protobuf:"varint,7,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	InheritEnv    *wrapperspb.BoolValue  `protobuf:"bytes,8,opt,name=inherit_env,json=inheritEnv,proto3" json:"inherit_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDaemonRequest) Reset() {
	*x = StartDaemonRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDaemonRequest) ProtoMessage() {}

func (x *StartDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDaemonRequest.ProtoReflect.Descriptor instead.
func (*StartDaemonRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{20}
}

func (x *StartDaemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartDaemonRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *StartDaemonRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartDaemonRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartDaemonRequest) GetUid() *wrapperspb.Int32Value {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *StartDaemonRequest) GetGid() *wrapperspb.Int32Value {
	if x != nil {
		return x.Gid
	}
	return nil
}

func (x *StartDaemonRequest) GetGroups() []uint32 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *StartDaemonRequest) GetInheritEnv() *wrapperspb.BoolValue {
	if x != nil {
		return x.InheritEnv
	}
	return nil
}

type DaemonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StoppedAt     string                 `protobuf:"bytes,6,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	Uid           uint32                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonInfo) Reset() {
	*x = DaemonInfo{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonInfo) ProtoMessage() {}

func (x *DaemonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonInfo.ProtoReflect.Descriptor instead.
func (*DaemonInfo) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{21}
}

func (x *DaemonInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaemonInfo) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *DaemonInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *DaemonInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *DaemonInfo) GetStoppedAt() string {
	if x != nil {
		return x.StoppedAt
	}
	return ""
}

func (x *DaemonInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DaemonInfo) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type ListDaemonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDaemonsRequest) Reset() {
	*x = ListDaemonsRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDaemonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDaemonsRequest) ProtoMessage() {}

func (x *ListDaemonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDaemonsRequest.ProtoReflect.Descriptor instead.
func (*ListDaemonsRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{22}
}

type ListDaemonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daemons       []*DaemonInfo          `protobuf:"bytes,1,rep,name=daemons,proto3" json:"daemons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDaemonsResponse) Reset() {
	*x = ListDaemonsResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDaemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDaemonsResponse) ProtoMessage() {}

func (x *ListDaemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDaemonsResponse.ProtoReflect.Descriptor instead.
func (*ListDaemonsResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{23}
}

func (x *ListDaemonsResponse) GetDaemons() []*DaemonInfo {
	if x != nil {
		return x.Daemons
	}
	return nil
}

type StopDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonRequest) Reset() {
	*x = StopDaemonRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonRequest) ProtoMessage() {}

func (x *StopDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonRequest.ProtoReflect.Descriptor instead.
func (*StopDaemonRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{24}
}

func (x *StopDaemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StopDaemonRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type StopDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDaemonResponse) Reset() {
	*x = StopDaemonResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDaemonResponse) ProtoMessage() {}

func (x *StopDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDaemonResponse.ProtoReflect.Descriptor instead.
func (*StopDaemonResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{25}
}

type StopAllDaemonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAllDaemonsRequest) Reset() {
	*x = StopAllDaemonsRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllDaemonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllDaemonsRequest) ProtoMessage() {}

func (x *StopAllDaemonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllDaemonsRequest.ProtoReflect.Descriptor instead.
func (*StopAllDaemonsRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{26}
}

type StopAllDaemonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daemons       []string               `protobuf:"bytes,1,rep,name=daemons,proto3" json:"daemons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAllDaemonsResponse) Reset() {
	*x = StopAllDaemonsResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllDaemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllDaemonsResponse) ProtoMessage() {}

func (x *StopAllDaemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllDaemonsResponse.ProtoReflect.Descriptor instead.
func (*StopAllDaemonsResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{27}
}

func (x *StopAllDaemonsResponse) GetDaemons() []string {
	if x != nil {
		return x.Daemons
	}
	return nil
}

type RestartDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDaemonRequest) Reset() {
	*x = RestartDaemonRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDaemonRequest) ProtoMessage() {}

func (x *RestartDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDaemonRequest.ProtoReflect.Descriptor instead.
func (*RestartDaemonRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{28}
}

func (x *RestartDaemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DaemonLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TailBytes     int32                  `protobuf:"varint,2,opt,name=tail_bytes,json=tailBytes,proto3" json:"tail_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonLogsRequest) Reset() {
	*x = DaemonLogsRequest{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonLogsRequest) ProtoMessage() {}

func (x *DaemonLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonLogsRequest.ProtoReflect.Descriptor instead.
func (*DaemonLogsRequest) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{29}
}

func (x *DaemonLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaemonLogsRequest) GetTailBytes() int32 {
	if x != nil {
		return x.TailBytes
	}
	return 0
}

type DaemonLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonLogsResponse) Reset() {
	*x = DaemonLogsResponse{}
	mi := &file_dshguest_v1_guest_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonLogsResponse) ProtoMessage() {}

func (x *DaemonLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dshguest_v1_guest_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonLogsResponse.ProtoReflect.Descriptor instead.
func (*DaemonLogsResponse) Descriptor() ([]byte, []int) {
	return file_dshguest_v1_guest_proto_rawDescGZIP(), []int{30}
}

func (x *DaemonLogsResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *DaemonLogsResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

var File_dshguest_v1_guest_proto protoreflect.FileDescriptor

const file_dshguest_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x17dshguest/v1/guest.proto\x12\vdshguest.v1\x1a\x1egoogle/protobuf/wrappers.proto\"i\n" +
	"\tExecInput\x12.\n" +
	"\x05start\x18\x01 \x01(\v2\x16.dshguest.v1.ExecStartH\x00R\x05start\x12!\n" +
	"\vstdin_chunk\x18\x02 \x01(\fH\x00R\n" +
	"stdinChunkB\t\n" +
	"\apayload\"\x9c\x01\n" +
	"\tExecStart\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x121\n" +
	"\x03env\x18\x03 \x03(\v2\x1f.dshguest.v1.ExecStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\n" +
	"ExecOutput\x12#\n" +
	"\fstdout_chunk\x18\x01 \x01(\fH\x00R\vstdoutChunk\x12#\n" +
	"\fstderr_chunk\x18\x02 \x01(\fH\x00R\vstderrChunk\x12+\n" +
	"\x04exit\x18\x03 \x01(\v2\x15.dshguest.v1.ExecExitH\x00R\x04exit\x12\x1d\n" +
	"\n" +
	"process_id\x18\x04 \x01(\tR\tprocessIdB\t\n" +
	"\apayload\"[\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1a\n" +
	"\bsignaled\x18\x02 \x01(\bR\bsignaled\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\"F\n" +
	"\rSignalRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x10\n" +
	"\x0eSignalResponse\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\rReadFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"q\n" +
	"\x0eWriteFileChunk\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1b.dshguest.v1.WriteFileStartH\x00R\x05start\x12\x1f\n" +
	"\n" +
	"data_chunk\x18\x02 \x01(\fH\x00R\tdataChunkB\t\n" +
	"\apayload\"X\n" +
	"\x0eWriteFileStart\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x12\x1a\n" +
	"\btruncate\x18\x03 \x01(\bR\btruncate\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x86\x01\n" +
	"\fStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1f\n" +
	"\vmodified_at\x18\x05 \x01(\tR\n" +
	"modifiedAt\"$\n" +
	"\x0eReadDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"B\n" +
	"\x0fReadDirResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.dshguest.v1.DirEntryR\aentries\"I\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"<\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aparents\x18\x02 \x01(\bR\aparents\"\x0f\n" +
	"\rMkdirResponse\"A\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x10\n" +
	"\x0eDeleteResponse\"\xf5\x02\n" +
	"\x12StartDaemonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12:\n" +
	"\x03env\x18\x04 \x03(\v2(.dshguest.v1.StartDaemonRequest.EnvEntryR\x03env\x12-\n" +
	"\x03uid\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\x03uid\x12-\n" +
	"\x03gid\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x03gid\x12\x16\n" +
	"\x06groups\x18\a \x03(\rR\x06groups\x12;\n" +
	"\vinherit_env\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"inheritEnv\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\n" +
	"DaemonInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x06 \x01(\tR\tstoppedAt\x12\x10\n" +
	"\x03uid\x18\a \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\b \x01(\rR\x03gid\"\x14\n" +
	"\x12ListDaemonsRequest\"H\n" +
	"\x13ListDaemonsResponse\x121\n" +
	"\adaemons\x18\x01 \x03(\v2\x17.dshguest.v1.DaemonInfoR\adaemons\"?\n" +
	"\x11StopDaemonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"\x14\n" +
	"\x12StopDaemonResponse\"\x17\n" +
	"\x15StopAllDaemonsRequest\"2\n" +
	"\x16StopAllDaemonsResponse\x12\x18\n" +
	"\adaemons\x18\x01 \x03(\tR\adaemons\"*\n" +
	"\x14RestartDaemonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x11DaemonLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"tail_bytes\x18\x02 \x01(\x05R\ttailBytes\"D\n" +
	"\x12DaemonLogsResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr2\x90\b\n" +
	"\x13WorkspaceGuestAgent\x12;\n" +
	"\x04Exec\x12\x16.dshguest.v1.ExecInput\x1a\x17.dshguest.v1.ExecOutput(\x010\x01\x12A\n" +
	"\x06Signal\x12\x1a.dshguest.v1.SignalRequest\x1a\x1b.dshguest.v1.SignalResponse\x12F\n" +
	"\bReadFile\x12\x1c.dshguest.v1.ReadFileRequest\x1a\x1a.dshguest.v1.ReadFileChunk0\x01\x12J\n" +
	"\tWriteFile\x12\x1b.dshguest.v1.WriteFileChunk\x1a\x1e.dshguest.v1.WriteFileResponse(\x01\x12;\n" +
	"\x04Stat\x12\x18.dshguest.v1.StatRequest\x1a\x19.dshguest.v1.StatResponse\x12D\n" +
	"\aReadDir\x12\x1b.dshguest.v1.ReadDirRequest\x1a\x1c.dshguest.v1.ReadDirResponse\x12>\n" +
	"\x05Mkdir\x12\x19.dshguest.v1.MkdirRequest\x1a\x1a.dshguest.v1.MkdirResponse\x12A\n" +
	"\x06Delete\x12\x1a.dshguest.v1.DeleteRequest\x1a\x1b.dshguest.v1.DeleteResponse\x12G\n" +
	"\vStartDaemon\x12\x1f.dshguest.v1.StartDaemonRequest\x1a\x17.dshguest.v1.DaemonInfo\x12P\n" +
	"\vListDaemons\x12\x1f.dshguest.v1.ListDaemonsRequest\x1a .dshguest.v1.ListDaemonsResponse\x12M\n" +
	"\n" +
	"StopDaemon\x12\x1e.dshguest.v1.StopDaemonRequest\x1a\x1f.dshguest.v1.StopDaemonResponse\x12Y\n" +
	"\x0eStopAllDaemons\x12\".dshguest.v1.StopAllDaemonsRequest\x1a#.dshguest.v1.StopAllDaemonsResponse\x12K\n" +
	"\rRestartDaemon\x12!.dshguest.v1.RestartDaemonRequest\x1a\x17.dshguest.v1.DaemonInfo\x12M\n" +
	"\n" +
	"DaemonLogs\x12\x1e.dshguest.v1.DaemonLogsRequest\x1a\x1f.dshguest.v1.DaemonLogsResponseBKZIgithub.com/Exagone313/dsh-podman/internal/genproto/dshguest/v1;dshguestv1b\x06proto3"

var (
	file_dshguest_v1_guest_proto_rawDescOnce sync.Once
	file_dshguest_v1_guest_proto_rawDescData []byte
)

func file_dshguest_v1_guest_proto_rawDescGZIP() []byte {
	file_dshguest_v1_guest_proto_rawDescOnce.Do(func() {
		file_dshguest_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dshguest_v1_guest_proto_rawDesc), len(file_dshguest_v1_guest_proto_rawDesc)))
	})
	return file_dshguest_v1_guest_proto_rawDescData
}

var file_dshguest_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_dshguest_v1_guest_proto_goTypes = []any{
	(*ExecInput)(nil),              // 0: dshguest.v1.ExecInput
	(*ExecStart)(nil),              // 1: dshguest.v1.ExecStart
	(*ExecOutput)(nil),             // 2: dshguest.v1.ExecOutput
	(*ExecExit)(nil),               // 3: dshguest.v1.ExecExit
	(*SignalRequest)(nil),          // 4: dshguest.v1.SignalRequest
	(*SignalResponse)(nil),         // 5: dshguest.v1.SignalResponse
	(*ReadFileRequest)(nil),        // 6: dshguest.v1.ReadFileRequest
	(*ReadFileChunk)(nil),          // 7: dshguest.v1.ReadFileChunk
	(*WriteFileChunk)(nil),         // 8: dshguest.v1.WriteFileChunk
	(*WriteFileStart)(nil),         // 9: dshguest.v1.WriteFileStart
	(*WriteFileResponse)(nil),      // 10: dshguest.v1.WriteFileResponse
	(*StatRequest)(nil),            // 11: dshguest.v1.StatRequest
	(*StatResponse)(nil),           // 12: dshguest.v1.StatResponse
	(*ReadDirRequest)(nil),         // 13: dshguest.v1.ReadDirRequest
	(*ReadDirResponse)(nil),        // 14: dshguest.v1.ReadDirResponse
	(*DirEntry)(nil),               // 15: dshguest.v1.DirEntry
	(*MkdirRequest)(nil),           // 16: dshguest.v1.MkdirRequest
	(*MkdirResponse)(nil),          // 17: dshguest.v1.MkdirResponse
	(*DeleteRequest)(nil),          // 18: dshguest.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 19: dshguest.v1.DeleteResponse
	(*StartDaemonRequest)(nil),     // 20: dshguest.v1.StartDaemonRequest
	(*DaemonInfo)(nil),             // 21: dshguest.v1.DaemonInfo
	(*ListDaemonsRequest)(nil),     // 22: dshguest.v1.ListDaemonsRequest
	(*ListDaemonsResponse)(nil),    // 23: dshguest.v1.ListDaemonsResponse
	(*StopDaemonRequest)(nil),      // 24: dshguest.v1.StopDaemonRequest
	(*StopDaemonResponse)(nil),     // 25: dshguest.v1.StopDaemonResponse
	(*StopAllDaemonsRequest)(nil),  // 26: dshguest.v1.StopAllDaemonsRequest
	(*StopAllDaemonsResponse)(nil), // 27: dshguest.v1.StopAllDaemonsResponse
	(*RestartDaemonRequest)(nil),   // 28: dshguest.v1.RestartDaemonRequest
	(*DaemonLogsRequest)(nil),      // 29: dshguest.v1.DaemonLogsRequest
	(*DaemonLogsResponse)(nil),     // 30: dshguest.v1.DaemonLogsResponse
	nil,                            // 31: dshguest.v1.ExecStart.EnvEntry
	nil,                            // 32: dshguest.v1.StartDaemonRequest.EnvEntry
	(*wrapperspb.Int32Value)(nil),  // 33: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),   // 34: google.protobuf.BoolValue
}
var file_dshguest_v1_guest_proto_depIdxs = []int32{
	1,  // 0: dshguest.v1.ExecInput.start:type_name -> dshguest.v1.ExecStart
	31, // 1: dshguest.v1.ExecStart.env:type_name -> dshguest.v1.ExecStart.EnvEntry
	3,  // 2: dshguest.v1.ExecOutput.exit:type_name -> dshguest.v1.ExecExit
	9,  // 3: dshguest.v1.WriteFileChunk.start:type_name -> dshguest.v1.WriteFileStart
	15, // 4: dshguest.v1.ReadDirResponse.entries:type_name -> dshguest.v1.DirEntry
	32, // 5: dshguest.v1.StartDaemonRequest.env:type_name -> dshguest.v1.StartDaemonRequest.EnvEntry
	33, // 6: dshguest.v1.StartDaemonRequest.uid:type_name -> google.protobuf.Int32Value
	33, // 7: dshguest.v1.StartDaemonRequest.gid:type_name -> google.protobuf.Int32Value
	34, // 8: dshguest.v1.StartDaemonRequest.inherit_env:type_name -> google.protobuf.BoolValue
	21, // 9: dshguest.v1.ListDaemonsResponse.daemons:type_name -> dshguest.v1.DaemonInfo
	0,  // 10: dshguest.v1.WorkspaceGuestAgent.Exec:input_type -> dshguest.v1.ExecInput
	4,  // 11: dshguest.v1.WorkspaceGuestAgent.Signal:input_type -> dshguest.v1.SignalRequest
	6,  // 12: dshguest.v1.WorkspaceGuestAgent.ReadFile:input_type -> dshguest.v1.ReadFileRequest
	8,  // 13: dshguest.v1.WorkspaceGuestAgent.WriteFile:input_type -> dshguest.v1.WriteFileChunk
	11, // 14: dshguest.v1.WorkspaceGuestAgent.Stat:input_type -> dshguest.v1.StatRequest
	13, // 15: dshguest.v1.WorkspaceGuestAgent.ReadDir:input_type -> dshguest.v1.ReadDirRequest
	16, // 16: dshguest.v1.WorkspaceGuestAgent.Mkdir:input_type -> dshguest.v1.MkdirRequest
	18, // 17: dshguest.v1.WorkspaceGuestAgent.Delete:input_type -> dshguest.v1.DeleteRequest
	20, // 18: dshguest.v1.WorkspaceGuestAgent.StartDaemon:input_type -> dshguest.v1.StartDaemonRequest
	22, // 19: dshguest.v1.WorkspaceGuestAgent.ListDaemons:input_type -> dshguest.v1.ListDaemonsRequest
	24, // 20: dshguest.v1.WorkspaceGuestAgent.StopDaemon:input_type -> dshguest.v1.StopDaemonRequest
	26, // 21: dshguest.v1.WorkspaceGuestAgent.StopAllDaemons:input_type -> dshguest.v1.StopAllDaemonsRequest
	28, // 22: dshguest.v1.WorkspaceGuestAgent.RestartDaemon:input_type -> dshguest.v1.RestartDaemonRequest
	29, // 23: dshguest.v1.WorkspaceGuestAgent.DaemonLogs:input_type -> dshguest.v1.DaemonLogsRequest
	2,  // 24: dshguest.v1.WorkspaceGuestAgent.Exec:output_type -> dshguest.v1.ExecOutput
	5,  // 25: dshguest.v1.WorkspaceGuestAgent.Signal:output_type -> dshguest.v1.SignalResponse
	7,  // 26: dshguest.v1.WorkspaceGuestAgent.ReadFile:output_type -> dshguest.v1.ReadFileChunk
	10, // 27: dshguest.v1.WorkspaceGuestAgent.WriteFile:output_type -> dshguest.v1.WriteFileResponse
	12, // 28: dshguest.v1.WorkspaceGuestAgent.Stat:output_type -> dshguest.v1.StatResponse
	14, // 29: dshguest.v1.WorkspaceGuestAgent.ReadDir:output_type -> dshguest.v1.ReadDirResponse
	17, // 30: dshguest.v1.WorkspaceGuestAgent.Mkdir:output_type -> dshguest.v1.MkdirResponse
	19, // 31: dshguest.v1.WorkspaceGuestAgent.Delete:output_type -> dshguest.v1.DeleteResponse
	21, // 32: dshguest.v1.WorkspaceGuestAgent.StartDaemon:output_type -> dshguest.v1.DaemonInfo
	23, // 33: dshguest.v1.WorkspaceGuestAgent.ListDaemons:output_type -> dshguest.v1.ListDaemonsResponse
	25, // 34: dshguest.v1.WorkspaceGuestAgent.StopDaemon:output_type -> dshguest.v1.StopDaemonResponse
	27, // 35: dshguest.v1.WorkspaceGuestAgent.StopAllDaemons:output_type -> dshguest.v1.StopAllDaemonsResponse
	21, // 36: dshguest.v1.WorkspaceGuestAgent.RestartDaemon:output_type -> dshguest.v1.DaemonInfo
	30, // 37: dshguest.v1.WorkspaceGuestAgent.DaemonLogs:output_type -> dshguest.v1.DaemonLogsResponse
	24, // [24:38] is the sub-list for method output_type
	10, // [10:24] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dshguest_v1_guest_proto_init() }
func file_dshguest_v1_guest_proto_init() {
	if File_dshguest_v1_guest_proto != nil {
		return
	}
	file_dshguest_v1_guest_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecInput_Start)(nil),
		(*ExecInput_StdinChunk)(nil),
	}
	file_dshguest_v1_guest_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecOutput_StdoutChunk)(nil),
		(*ExecOutput_StderrChunk)(nil),
		(*ExecOutput_Exit)(nil),
	}
	file_dshguest_v1_guest_proto_msgTypes[8].OneofWrappers = []any{
		(*WriteFileChunk_Start)(nil),
		(*WriteFileChunk_DataChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dshguest_v1_guest_proto_rawDesc), len(file_dshguest_v1_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dshguest_v1_guest_proto_goTypes,
		DependencyIndexes: file_dshguest_v1_guest_proto_depIdxs,
		MessageInfos:      file_dshguest_v1_guest_proto_msgTypes,
	}.Build()
	File_dshguest_v1_guest_proto = out.File
	file_dshguest_v1_guest_proto_goTypes = nil
	file_dshguest_v1_guest_proto_depIdxs = nil
}
