// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dshguest/v1/guest.proto

package dshguestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceGuestAgent_Exec_FullMethodName          = "/dshguest.v1.WorkspaceGuestAgent/Exec"
	WorkspaceGuestAgent_Signal_FullMethodName        = "/dshguest.v1.WorkspaceGuestAgent/Signal"
	WorkspaceGuestAgent_ListProcesses_FullMethodName = "/dshguest.v1.WorkspaceGuestAgent/ListProcesses"
	WorkspaceGuestAgent_ReadFile_FullMethodName      = "/dshguest.v1.WorkspaceGuestAgent/ReadFile"
	WorkspaceGuestAgent_WriteFile_FullMethodName     = "/dshguest.v1.WorkspaceGuestAgent/WriteFile"
	WorkspaceGuestAgent_Stat_FullMethodName          = "/dshguest.v1.WorkspaceGuestAgent/Stat"
	WorkspaceGuestAgent_ReadDir_FullMethodName       = "/dshguest.v1.WorkspaceGuestAgent/ReadDir"
	WorkspaceGuestAgent_Mkdir_FullMethodName         = "/dshguest.v1.WorkspaceGuestAgent/Mkdir"
	WorkspaceGuestAgent_Delete_FullMethodName        = "/dshguest.v1.WorkspaceGuestAgent/Delete"
	WorkspaceGuestAgent_StartDaemon_FullMethodName   = "/dshguest.v1.WorkspaceGuestAgent/StartDaemon"
	WorkspaceGuestAgent_ListDaemons_FullMethodName   = "/dshguest.v1.WorkspaceGuestAgent/ListDaemons"
	WorkspaceGuestAgent_StopDaemon_FullMethodName    = "/dshguest.v1.WorkspaceGuestAgent/StopDaemon"
	WorkspaceGuestAgent_RestartDaemon_FullMethodName = "/dshguest.v1.WorkspaceGuestAgent/RestartDaemon"
	WorkspaceGuestAgent_DaemonLogs_FullMethodName    = "/dshguest.v1.WorkspaceGuestAgent/DaemonLogs"
)

// WorkspaceGuestAgentClient is the client API for WorkspaceGuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceGuestAgentClient interface {
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileChunk], error)
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse], error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	StartDaemon(ctx context.Context, in *StartDaemonRequest, opts ...grpc.CallOption) (*DaemonInfo, error)
	ListDaemons(ctx context.Context, in *ListDaemonsRequest, opts ...grpc.CallOption) (*ListDaemonsResponse, error)
	StopDaemon(ctx context.Context, in *StopDaemonRequest, opts ...grpc.CallOption) (*StopDaemonResponse, error)
	RestartDaemon(ctx context.Context, in *RestartDaemonRequest, opts ...grpc.CallOption) (*DaemonInfo, error)
	DaemonLogs(ctx context.Context, in *DaemonLogsRequest, opts ...grpc.CallOption) (*DaemonLogsResponse, error)
}

type workspaceGuestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceGuestAgentClient(cc grpc.ClientConnInterface) WorkspaceGuestAgentClient {
	return &workspaceGuestAgentClient{cc}
}

func (c *workspaceGuestAgentClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceGuestAgent_ServiceDesc.Streams[0], WorkspaceGuestAgent_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_ExecClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *workspaceGuestAgentClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceGuestAgent_ServiceDesc.Streams[1], WorkspaceGuestAgent_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, ReadFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_ReadFileClient = grpc.ServerStreamingClient[ReadFileChunk]

func (c *workspaceGuestAgentClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceGuestAgent_ServiceDesc.Streams[2], WorkspaceGuestAgent_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileChunk, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_WriteFileClient = grpc.ClientStreamingClient[WriteFileChunk, WriteFileResponse]

func (c *workspaceGuestAgentClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (*ReadDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDirResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_ReadDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) StartDaemon(ctx context.Context, in *StartDaemonRequest, opts ...grpc.CallOption) (*DaemonInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonInfo)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_StartDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) ListDaemons(ctx context.Context, in *ListDaemonsRequest, opts ...grpc.CallOption) (*ListDaemonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDaemonsResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_ListDaemons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) StopDaemon(ctx context.Context, in *StopDaemonRequest, opts ...grpc.CallOption) (*StopDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDaemonResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_StopDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) RestartDaemon(ctx context.Context, in *RestartDaemonRequest, opts ...grpc.CallOption) (*DaemonInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonInfo)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_RestartDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceGuestAgentClient) DaemonLogs(ctx context.Context, in *DaemonLogsRequest, opts ...grpc.CallOption) (*DaemonLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonLogsResponse)
	err := c.cc.Invoke(ctx, WorkspaceGuestAgent_DaemonLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceGuestAgentServer is the server API for WorkspaceGuestAgent service.
// All implementations must embed UnimplementedWorkspaceGuestAgentServer
// for forward compatibility.
type WorkspaceGuestAgentServer interface {
	Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileChunk]) error
	WriteFile(grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]) error
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ReadDir(context.Context, *ReadDirRequest) (*ReadDirResponse, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	StartDaemon(context.Context, *StartDaemonRequest) (*DaemonInfo, error)
	ListDaemons(context.Context, *ListDaemonsRequest) (*ListDaemonsResponse, error)
	StopDaemon(context.Context, *StopDaemonRequest) (*StopDaemonResponse, error)
	RestartDaemon(context.Context, *RestartDaemonRequest) (*DaemonInfo, error)
	DaemonLogs(context.Context, *DaemonLogsRequest) (*DaemonLogsResponse, error)
	mustEmbedUnimplementedWorkspaceGuestAgentServer()
}

// UnimplementedWorkspaceGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceGuestAgentServer struct{}

func (UnimplementedWorkspaceGuestAgentServer) Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) WriteFile(grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) ReadDir(context.Context, *ReadDirRequest) (*ReadDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDir not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) StartDaemon(context.Context, *StartDaemonRequest) (*DaemonInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDaemon not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) ListDaemons(context.Context, *ListDaemonsRequest) (*ListDaemonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDaemons not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) StopDaemon(context.Context, *StopDaemonRequest) (*StopDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDaemon not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) RestartDaemon(context.Context, *RestartDaemonRequest) (*DaemonInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartDaemon not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) DaemonLogs(context.Context, *DaemonLogsRequest) (*DaemonLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonLogs not implemented")
}
func (UnimplementedWorkspaceGuestAgentServer) mustEmbedUnimplementedWorkspaceGuestAgentServer() {}
func (UnimplementedWorkspaceGuestAgentServer) testEmbeddedByValue()                             {}

// UnsafeWorkspaceGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceGuestAgentServer will
// result in compilation errors.
type UnsafeWorkspaceGuestAgentServer interface {
	mustEmbedUnimplementedWorkspaceGuestAgentServer()
}

func RegisterWorkspaceGuestAgentServer(s grpc.ServiceRegistrar, srv WorkspaceGuestAgentServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceGuestAgent_ServiceDesc, srv)
}

func _WorkspaceGuestAgent_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkspaceGuestAgentServer).Exec(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_ExecServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _WorkspaceGuestAgent_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceGuestAgentServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, ReadFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_ReadFileServer = grpc.ServerStreamingServer[ReadFileChunk]

func _WorkspaceGuestAgent_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkspaceGuestAgentServer).WriteFile(&grpc.GenericServerStream[WriteFileChunk, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceGuestAgent_WriteFileServer = grpc.ClientStreamingServer[WriteFileChunk, WriteFileResponse]

func _WorkspaceGuestAgent_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_ReadDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).ReadDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_ReadDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).ReadDir(ctx, req.(*ReadDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_StartDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).StartDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_StartDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).StartDaemon(ctx, req.(*StartDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_ListDaemons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDaemonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).ListDaemons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_ListDaemons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).ListDaemons(ctx, req.(*ListDaemonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_StopDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).StopDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_StopDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).StopDaemon(ctx, req.(*StopDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_RestartDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).RestartDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_RestartDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).RestartDaemon(ctx, req.(*RestartDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceGuestAgent_DaemonLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceGuestAgentServer).DaemonLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceGuestAgent_DaemonLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceGuestAgentServer).DaemonLogs(ctx, req.(*DaemonLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceGuestAgent_ServiceDesc is the grpc.ServiceDesc for WorkspaceGuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceGuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dshguest.v1.WorkspaceGuestAgent",
	HandlerType: (*WorkspaceGuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signal",
			Handler:    _WorkspaceGuestAgent_Signal_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _WorkspaceGuestAgent_ListProcesses_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _WorkspaceGuestAgent_Stat_Handler,
		},
		{
			MethodName: "ReadDir",
			Handler:    _WorkspaceGuestAgent_ReadDir_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _WorkspaceGuestAgent_Mkdir_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WorkspaceGuestAgent_Delete_Handler,
		},
		{
			MethodName: "StartDaemon",
			Handler:    _WorkspaceGuestAgent_StartDaemon_Handler,
		},
		{
			MethodName: "ListDaemons",
			Handler:    _WorkspaceGuestAgent_ListDaemons_Handler,
		},
		{
			MethodName: "StopDaemon",
			Handler:    _WorkspaceGuestAgent_StopDaemon_Handler,
		},
		{
			MethodName: "RestartDaemon",
			Handler:    _WorkspaceGuestAgent_RestartDaemon_Handler,
		},
		{
			MethodName: "DaemonLogs",
			Handler:    _WorkspaceGuestAgent_DaemonLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _WorkspaceGuestAgent_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFile",
			Handler:       _WorkspaceGuestAgent_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _WorkspaceGuestAgent_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dshguest/v1/guest.proto",
}
