// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Generate src/generated/version.ts from the current git state so the plugin
// carries the same tag-derived version and commit as the Go binaries. The
// generated file is gitignored and produced at build/typecheck time.
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

function git(args) {
  try {
    return execSync(`git ${args}`, {
      encoding: "utf8",
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

const describe = git("describe --tags");
const commit = git("rev-parse --short HEAD");
const version = describe || "dev";

const dir = join(root, "src", "generated");
mkdirSync(dir, { recursive: true });
writeFileSync(
  join(dir, "version.ts"),
  `// SPDX-FileCopyrightText: 2026 Elouan Martinet <exa@elou.world>
//
// SPDX-License-Identifier: MIT

// Generated by scripts/generate-version.mjs; do not edit.
export const VERSION = ${JSON.stringify(version)};
export const GIT_COMMIT = ${JSON.stringify(commit || "unknown")};
`,
);
console.log(`generated version ${version}@${commit || "unknown"}`);
